### ISSUE TITLE
INFO SESSION | OKITIPUPA - 2021/07/08

### ISSUE THREAD

**Issue by olawanlejoel** [oscafrica/chapter-leads-hub#16]
## Event information
_Please complete all applicable._

- **Event name**: OSCA OKITIPUPA : INFO SESSION
- **Event date**: _2021/07/08_
- **Estimated number of attendees**: 50
- **Event location**: Google Meet
- **Event description**: This event is to intimate everybody interested in becoming a part of this community with what this community is all about, her guidelines, code of conduct and lot’s more.

## How does this benefit your chapter?
_Please let us know why we should approve this event._

This event will build a solid foundation for everyone interested in becoming part of this community with what this community is all about, her guidelines, code of conduct.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Just basic materials, If any.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) for sponsorship.

**Before the event**: 
- [x] Your event is approved.
- [ ] Your event's RSVP page has been created on [Open Collective](https://opencollective/osca).
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all related expense receipts for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Hey @olawanlejoel. Thanks for submitting this ticket. 😀

This looks good to me. Please go ahead and start making the necessary arrangements. Would you love us to share your event via OSCA's official social media pages? If yes, send me the necessary materials on Discord when you are ready. 

We're super proud of you and your community and can't wait to see you shine.

**Comment by olawanlejoel** [comment]
Thanks so much, @didicodes . I will do share materials as soon as they are ready to go out!

**Comment by BolajiAyodeji** [comment]
Hi @olawanlejoel, you have not submitted your post event report yet. Kindly use the [Post Event Template](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md) and submit your report so we can review and close this issue. Thank you!

**Comment by olawanlejoel** [comment]
So sorry for the delay @BolajiAyodeji, Our next events would be faster and smoother. I am sending the report now!

**Comment by olawanlejoel** [comment]
# Post Event Report [INFO SESSION | OKITIPUPA] [2021/07/08]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_
About 35 people attended the event

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_
The event was a virtual one and it held on Google meet.

## The Good, Bad, and Ugly 🔴

_Feel free to share your positive and negative experiences here with bullet points._
It was a really great one in which most of the participants were students.
 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_
Seriously, It was very difficult kickstarting a community, the whole pressure, I had to shift the date but I am very happy it finally hed and I was able to pull a really great one which left everyone expectant.


## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_

## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_
![IMG_0371](https://user-images.githubusercontent.com/57611810/125908240-edffeb1b-e34a-466b-bf9b-d6aabf5e7267.jpg)
![IMG_0372](https://user-images.githubusercontent.com/57611810/125908256-4ac9cced-5401-41b8-8975-fe508ef8dee3.jpg)


## Summary 🟡

_Generally, what's your overview of the event?_
It was really successful and it was a good start.

_How did it go for you as a Chapter Lead?_
It went really well, I started the event by explaining what OSCA is all about, her mission and everything about the community, Then I also spoke about open source and it's differnt arreas such as code, writing and design so everyone can feel at home.

_Looking forward to the next event? What changes will you be making based on your experience from this event?_
As I promised them, we will be having workshops on getting started with open source as a developer, designer and writer.

**Comment by olawanlejoel** [comment]
so sorry, I was supposed to take screenshot of my screen, I will do that next time.

**Comment by BolajiAyodeji** [comment]
Hi @olawanlejoel, congratulations on your first event. I'm glad you learned a lot, and we look forward to your next. Keep the fire burning, champ!
