### ISSUE TITLE
MEETUP AND ONBOARDING EVENT| LEKKI-AJAH - 2021/05/29

### ISSUE THREAD

**Issue by AbisoyeAlli** [oscafrica/chapter-leads-hub#17]
> Before you start, please follow the issue title format and assign yourself to this issue.

> If the event is a multiple date event, only add the starting date in the title.

> Please note that we need **2 weeks minimum and 3 weeks maximum notice** to approve proposed events.

> Please note that we need **21 days maximum notice** to provide support from your request.

## Event information
_Please complete all applicable._

- **Event name**: Meetup and Onboarding event
- **Event date**: _2021/05 /29_
- **Estimated number of attendees**:  15
- **Event location**: Lekki Conservation Center, LCC. 
- **Event description**: The very first physical Meetup of the Lekki-Ajah chapter. It is aimed towards onboarding members of the chapter about OSCA, goals of the chapter, planning the trajectory of the chapter for the next few months, getting and curating ideas from team members. It is also an opportunity to really get to know one another. 

## How does this benefit your chapter?
This event is essential to the success of this chapter as it presents and opportunity to know each other better and give every member a sense of responsibility and community as we all plan the trajectory of this chapter together. 

## What help do you need with this event? 
All members volunteered to pay their gate fee and bring snacks as well, hence, no financial assistance is required at this time. We would appreciate retweets and postings from the community once the e-flier is completed and approved. 

## Checklist

**Before you post the issue**: 
- [X] You have followed the issue title format.
- [X] You have applied the correct labels (Country, Type of Event, Requests).
- [X] You have completed the [request form](https://bit.ly/osca-cl-request) for sponsorship.

**Before the event**: 
- [X] Your event is approved.
- [ ] Your event's RSVP page has been created on [Open Collective](https://opencollective/osca).
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [X] You have completed the [post-event report](/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all related expense receipts for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Hey @AbisoyeAlli. Thanks for submitting this ticket. 😀 

As discussed on Discord, we expect the attendees to follow the COVID 19 safety precautions to stay safe from the virus.

We would gladly help you spread the word via our social media channels. Please share the designs and content with us via Discord when they are ready. 

I noticed you also submitted the **[request form for sponsorship form](https://bit.ly/osca-cl-request)** even though you didn't need money for this event. Please only fill this form when you need financial support for your event. 

Other than that, this looks good to me. So, you can go ahead and start making the necessary arrangements. We're super proud of you and your community and can't wait to see you shine.

**Comment by AbisoyeAlli** [comment]
Thank you @didicodes 

We will commence necessary arrangements immediately.

**Comment by AbisoyeAlli** [comment]
# Post Event Report [MEETUP AND ONBOARDING EVENT LEKKI-AJAH CHAPTER] [29/05/2021]


## Attendance 🔵

We had an attendance of 10 including me. We had 2 ladies and 8 gents, all either ibo or yoruba.

## Event Venue 🟣

We used the Lekki Conservation Center. It was a good place for the first meetup, it really helped relax the mood. No difficulty at all.

## The Good, Bad, and Ugly 🔴

Everything worked well except the schedule. We planned to start at 2pm but we could not start untill 4pm due to the bad weather and members caught in traffic. But we were able to achieve the goal of introducing members to the chapter and OSCA at large, we were able to have a mini workshop where every member in attendance made their first PR.

## TIL (Today I Learned) ⚪️

I learned that people really want be part of community. Also, open source is not a familiar concept to everyone, hence, a lot of work still needs to be done in raising the next billion creators.

## Feedback from Attendees 🟠

I got to speak with members at the end of the meetup and it was amazing. They really appreciated the workshop session where they contributed to the chapter  repository. Have a look at the PRs by the attendees [here](https://github.com/OSCA-Lekki-Ajah/Members-Directory/blob/main/NAMES.md)

## Social Media Highlights ⚫️

Our twitter account is still suspended.

## Event Photos 🟢

[Event images](https://github.com/OSCA-Lekki-Ajah/1st_meetup_gallery_29-5-2021)

## Summary 🟡

- The event fulfilled its purpose, I look fprward to the next one.

- As the chapter lead, it was great. I was afraid thing won't go as planned because of the rain but people showed up regardless (though late). I genuinely had a great time meeting everyone.

- Definitely. I am really looking forward to the next event. From my experience, I would secure a better venue, make arrangements for better refreshment and also have more workshops session.

**Comment by didicodes** [comment]
Thanks for hosting an amazing event in your community and also sharing a detailed update with us @AbisoyeAlli. It looked like a really fantastic event. It's good to see know you and the attendees had an amazing and insightful time together. 

#### Questions 😃
 
* Is there any update on your Twitter account? 
* How do you plan to follow up with the people who attended the event to ensure they still like a part of the community until your next virtual or in-person event?

**Comment by AbisoyeAlli** [comment]
Thank you @didicodes, we really did.

- Yes, we opened a new Twitter account. The new handle is @/oscalekkiajah

- We have grown from 9 to 24 in the past few weeks. Its still quite convenient to chat with members but I realize it is not sustainable. 
I appointed two members (a lady and a guy) to work closely with me as co-leads to help with correspondence, and develop a weekly chapter newsletter centered around open source and career. 

We also have a team of 4 members working on an open source project we agreed on (a web application that shows restaurants in the Lekki-Ajah area. A restaurant directory). This has helped sustained engagement within the chapter.

**Comment by didicodes** [comment]
> Yes, we opened a new Twitter account. The new handle is @/oscalekkiajah.

That's fantastic. I hope they don't ban this account as well. 

> We have grown from 9 to 24 in the past few weeks. It's still quite convenient to chat with members, but I realize it is not sustainable. I appointed two members (a lady and a guy) to work closely with me as co-leads to help with correspondence and develop a weekly chapter newsletter centered around open source and career.
Alright, that works 😃.

> We also have a team of 4 members working on an Open Source project we agreed on (a web application that shows restaurants in the Lekki-Ajah area. A restaurant directory). This has helped sustained engagement within the chapter.

Yes, I agree with you. This is an amazing initiative, @AbisoyeAlli. I can't wait to see what the web app will look like when it is completed. 

Once again, thanks for hosting an amazing and successful at OSCA Ajah.

**Comment by AbisoyeAlli** [comment]
I hope so too. We used a new phone number and email address, so we should be fine.

Thank you @didicodes
