### ISSUE TITLE
INTRODUCTION TO OPEN SOURCE AND WELCOME TO THE COMMUNITY | ENUGU- 2021/06/05

### ISSUE THREAD

**Issue by Veri5ied** [oscafrica/chapter-leads-hub#18]
> Before you start, please follow the issue title format and assign yourself to this issue.

> If the event is a multiple date event, only add the starting date in the title.

> Please note that we need **2 weeks minimum and 3 weeks maximum notice** to approve proposed events.

> Please note that we need **21 days maximum notice** to provide support from your request.

## Event information
_Please complete all applicable._

- **Event name**: INTRODUCTION TO OPEN SOURCE
- **Event date**: _2021/06/05_
- **Estimated number of attendees**: 20
- **Event location**: Google Meet
- **Event description**: An opportunity to welcome all community members as well as let the know about the OSCA chapter in the state, the leads, what the community is all about and how we would work together to achieve one goal which is to help all get started or to keep contributing in open source

## How does this benefit your chapter?
_Please let us know why we should approve this event._

This event is more like a stepping stone to the so many events we have in store for our community members. We want all to see that there is more to just contributing to Open source. An introduction to open source would eventually lead to why contribute to open source and this we want to print on hearts and minds of our community members.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._

A basic material from OSCA and also a little write-up on history of OSCA (we want to help people see the growth) and yeah data plan cause we'll be using Google meet :)

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) for sponsorship.

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created on [Open Collective](https://opencollective/osca).
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [x] You have submitted all related expense receipts for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @Veri5ied, thanks for submitting this issue.

Can you update the "YYYY/MM/DD" in the title to reflect the actual date, please?

**Comment by Veri5ied** [comment]
> Hi @Veri5ied, thanks for submitting this issue.
> 
> Can you update the "YYYY/MM/DD" in the title to reflect the actual date, please?

Sorry about that. It's done

**Comment by BolajiAyodeji** [comment]
Hi @Veri5ied, thank you once again!

This looks good to me; great work! Please go ahead and start making the necessary arrangements. We would create your event page on Open Collective and get back to you. Do share with us your event flyer if you have any as soon as possible.

Looking forward to your post-event report, cheers!

**Comment by Veri5ied** [comment]
Thank you very much

**Comment by BolajiAyodeji** [comment]
Hi @Veri5ied, here's your event link: https://opencollective.com/osca/events/osca-enugu-introduction-to-open-source-and-welcome-to-the-community-6fb449ad. Your attendees can register using the free Attendee ticket.

Kindly let us know the actual time of the event, thank you!

**Comment by Veri5ied** [comment]
The time for the event is 4:00pm @BolajiAyodeji and I have a question. What if we have more than 20 members ready to join, how can the free ticket be increased from 20 to a certain number?

**Comment by BolajiAyodeji** [comment]
Hi, the time is updated now! Yes, we can increase the ticket numbers. We set the limit to 20 based on your estimate, but if you max out the 20, do let us know, and we'll increase it for you.

**Comment by Veri5ied** [comment]
![Frame 1(1)](https://user-images.githubusercontent.com/43749581/119425769-e1729f80-bcff-11eb-9c96-22159c0844e3.png)

**Comment by BolajiAyodeji** [comment]
Hi @Veri5ied,

How do you intend to use your data request for yourself and share it with your community members? Can you share your plan, please?

**Comment by Veri5ied** [comment]
Hello @BolajiAyodeji,

We'll be having a guest speaker and from the data request, we'll appreciate her by covering her data expenses. Also some (not many though) community members who showed interest in attending the event talked about having little/no data to stay for the few hours we'll spend on Google Meet. So we (myself and my co-lead) want to help such ones who showed interest in attending the event so they don't miss out.

**Comment by BolajiAyodeji** [comment]
Hi @Veri5ied, thanks for the update.

And 3,000 NGN will be sufficient for this, right?

**Comment by Veri5ied** [comment]
Yes @BolajiAyodeji going by the number we have currently.
Thank you

**Comment by Veri5ied** [comment]
# Post Event Report [INTRODUCTION TO OPEN SOURCE AND WELCOME TO THE COMMUNITY | ENUGU] [2021/06/05]


## Attendance 🔵

We had over 15 in attendance during the event via google meet of which they really participated.

## Event Venue 🟣

We made use of Google meet. No much challenges aside from joining late of interested individuals of which I know we’d do better next time.

## The Good, Bad, and Ugly 🔴

All plans worked fine aside from the sponsor request which was carried out late but we really appreciate what the OSCA team did. At least they had us in mind and didn’t forget us.
 

## TIL (Today I Learned) ⚪️

I learnt that although one person can organize an event but having your team at heart and getting their opinions/suggestions together would go a long way to make the work very easy for you


## Feedback from Attendees 🟠

No aside wishing we’ll have a physical meetup so we can see and meet each other.

After the event during our Q & A session

## Social Media Highlights ⚫️
https://twitter.com/oscaenugu/status/1396913879389720578?s=19



## Summary 🟡

_Generally, what's your overview of the event?_
It was a nice one and we want more of this

_How did it go for you as a Chapter Lead?_
Honestly, it went well. Below is a summary of what was covered and also the slides used by our guest speaker:

First Part Summary:

https://docs.google.com/document/d/15T_t5ImJ5TV-wAYQIjfNBLhIQOwAMxBiaALUi95YcUg/edit?usp=sharing

Link to Slide on Introduction to Open Source:
https://drive.google.com/file/d/1gsXjtSu4mJwTSnrtydBhcYQiq59jalYD/view?usp=sharing


_Looking forward to the next event? What changes will you be making based on your experience from this event?_
The timing and also will make it an interactive one where everyone gets to say something and not just listen

Thank you @osca

**Comment by BolajiAyodeji** [comment]
Hi @Veri5ied,

Thanks for the very detailed post event report; your event was great! We're glad that everything went well and we look forward to more. Our sincere apologies for attending to your financial request very late.

Great work!

**Comment by BolajiAyodeji** [comment]
Hi @Veri5ied, have you submitted your receipts yet? Kindly ensure to read [this](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) and follow the process to submit your expenses. Thank you!
