### ISSUE TITLE
INTRODUCTION TO OPEN SOURCE | ADO EKITI - 2021/05/28

### ISSUE THREAD

**Issue by saintmalik** [oscafrica/chapter-leads-hub#19]
## Event information
_Please complete all applicable._

- **Event name**: INTRODUCTION TO OPEN SOURCE
- **Event date**: 2021/05/28
- **Estimated number of attendees**: 30-50
- **Event location**: Virtual (Google Meet)
- **Event description**: This will be the first open source event/meetup we will be having and alot of people do not have a solid background of what Open Source is all about and what OSCA is, so this event will center on introducing Open Source Community to them, why they should contribute to open source, the benefit and importance of contributing to Open Source.

## How does this benefit your chapter?
_Please let us know why we should approve this event._
This will be the first open source event/meetup we will be having and alot of people do not have a solid background of what Open Source is all about and what OSCA is, so this event will center on introducing Open Source Community to them, why they should contribute to open source, the benefit and importance of contributing to Open Source.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Nothing actually, all i need is event approval to proceed, we have our speaker on ground already

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) for sponsorship.

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created on [Open Collective](https://opencollective/osca).
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](/docs/post-event-template.md).
- [ ] You have submitted all related expense receipts for this event.
- [ ] This issue is closed.

**Comment by saintmalik** [comment]
@BolajiAyodeji Hello sir, please can you look into this.

**Comment by BolajiAyodeji** [comment]
Hi @saintmalik, thanks for submitting this issue, and apologies for the delayed response.

This looks good to me; great work! Please go ahead and start making the necessary arrangements. We would create your event page on Open Collective and get back to you. Do share with us your event flyer if you have any as soon as possible.

Looking forward to your post-event report, cheers!

**Comment by saintmalik** [comment]
> Hi @saintmalik, thanks for submitting this issue, and apologies for the delayed response.
> 
> This looks good to me; great work! Please go ahead and start making the necessary arrangements. We would create your event page on Open Collective and get back to you. Do share with us your event flyer if you have any as soon as possible.
> 
> Looking forward to your post-event report, cheers!

Thank you sir, all arrangements are in place, we waiting for the opencollective event url to start sharing out the fliers actually, so people wont visit an empty url yet.

Here is out flyer:

![WhatsApp Image 2021-05-23 at 10 56 49 AM](https://user-images.githubusercontent.com/37118134/119283082-d18d8980-bc33-11eb-9b0a-80599c99fe92.jpeg)

**Comment by BolajiAyodeji** [comment]
Hi @saintmalik, here's your event link: https://opencollective.com/osca-ado-ekiti-introduction-to-open-source-f5907782. Your attendees can register using the free **Attendee ticket**.

Kindly let us know the actual time of the event, thank you!

**Comment by saintmalik** [comment]
> Hi @saintmalik, here's your event link: https://opencollective.com/osca-ado-ekiti-introduction-to-open-source-f5907782. Your attendees can register using the free **Attendee ticket**.
> 
> Kindly let us know the actual time of the event, thank you!

6pm to 7pm, Nigeria time.

**Comment by saintmalik** [comment]
Can we change the time early, so as not to confuse people registering

**Comment by BolajiAyodeji** [comment]
Time changed! Thank you and good luck with your event.

**Comment by saintmalik** [comment]
Also sir, how do I link the event Google Meet and notify registered users 30 mij before event starts l

**Comment by BolajiAyodeji** [comment]
You can email your attendees with the link to your stream via a special email. I'll communicate that to you privately; thanks!

**Comment by saintmalik** [comment]
Okay thanks

**Comment by saintmalik** [comment]
# Post Event Report [INTRODUCTION TO OPEN SOURCE | OSCA ADO EKITI] [28/05/2021]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_

Yeah, attendances ranges between 11-16, yeah, there were'nt availability of girls attending the event.

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_

It was totally online, Google Meet

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_

_Feel free to share your positive and negative experiences here with bullet points._

- Had issues with sending a mail notifications to members about the event 30 minutes to the event due to the fact that i was sending to the wrong open collective email address.
- Few people came compare to the number of signups and group member.
- Yeah the little people who turned up were responsive.
- Also happy i made some impact even if the members attending the event wasnt as much as expected.
 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_

- Learnt how it is like to organize an event.
- Getting people to speak at my event
- New things about open source
- Met new people


## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_

https://twitter.com/emmy_respect/status/1398347745350586371

https://twitter.com/Slimmy_Tee_/status/1398352599632564226?s=20

https://twitter.com/dev_sproff/status/1398351379018682375?s=20

https://twitter.com/saintmalik_/status/1398347998862753798?s=20

https://twitter.com/know_dfj/status/1396739264122134530?s=20

https://twitter.com/emaz4me/status/1398356858356781059?s=20

https://twitter.com/rainleander/status/1398324507774009346?s=20

https://twitter.com/CockroachDB/status/1398290612957290497?s=20

## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_

![Screenshot 2021-05-28 at 5 56 05 PM](https://user-images.githubusercontent.com/37118134/120035885-37449180-bff7-11eb-850e-5946d39b4f7f.jpg)
![Screenshot 2021-05-28 at 5 59 59 PM](https://user-images.githubusercontent.com/37118134/120035896-3c094580-bff7-11eb-8072-1dd456a6db9f.jpg)
![Screenshot 2021-05-28 at 6 01 14 PM](https://user-images.githubusercontent.com/37118134/120035898-3d3a7280-bff7-11eb-882d-595b076d9a77.jpg)
![Screenshot 2021-05-28 at 6 04 22 PM](https://user-images.githubusercontent.com/37118134/120035901-3e6b9f80-bff7-11eb-8ed6-6fc3beae1415.jpg)
![Screenshot 2021-05-28 at 6 08 17 PM](https://user-images.githubusercontent.com/37118134/120035910-40356300-bff7-11eb-83b8-35446293e3b1.jpg)
![Screenshot 2021-05-28 at 6 19 03 PM](https://user-images.githubusercontent.com/37118134/120035916-40cdf980-bff7-11eb-970d-e50b6b18e829.jpg)
![Screenshot 2021-05-28 at 6 23 39 PM](https://user-images.githubusercontent.com/37118134/120035919-41ff2680-bff7-11eb-803b-932511164e21.jpg)
![Screenshot 2021-05-28 at 6 33 50 PM](https://user-images.githubusercontent.com/37118134/120035920-4297bd00-bff7-11eb-94db-82338a509b40.jpg)
![Screenshot 2021-05-28 at 6 40 47 PM](https://user-images.githubusercontent.com/37118134/120035924-43305380-bff7-11eb-9d8d-14643045d56f.jpg)
![Screenshot 2021-05-28 at 6 44 50 PM](https://user-images.githubusercontent.com/37118134/120035928-44fa1700-bff7-11eb-8040-05dba6bb2784.jpg)
![Screenshot 2021-05-28 at 6 52 37 PM](https://user-images.githubusercontent.com/37118134/120035932-4592ad80-bff7-11eb-8f67-dfea9e8bcab4.jpg)
![Screenshot 2021-05-28 at 6 53 09 PM](https://user-images.githubusercontent.com/37118134/120035933-462b4400-bff7-11eb-92d5-9255594271d3.jpg)
![Screenshot 2021-05-28 at 7 40 11 PM](https://user-images.githubusercontent.com/37118134/120035937-46c3da80-bff7-11eb-82d8-6d117be2c342.jpg)
![Screenshot 2021-05-28 at 7 40 36 PM](https://user-images.githubusercontent.com/37118134/120035942-47f50780-bff7-11eb-93e2-3d7eb88a8f39.jpg)
![Screenshot 2021-05-28 at 7 40 57 PM](https://user-images.githubusercontent.com/37118134/120035946-488d9e00-bff7-11eb-854f-e9bbd9c1890d.jpg)
![Screenshot 2021-05-28 at 7 41 15 PM](https://user-images.githubusercontent.com/37118134/120035948-49263480-bff7-11eb-9661-86036f34c919.jpg)
![Screenshot 2021-05-28 at 7 41 37 PM](https://user-images.githubusercontent.com/37118134/120035950-49becb00-bff7-11eb-972e-40f467b13846.jpg)
![Screenshot 2021-05-28 at 7 41 59 PM](https://user-images.githubusercontent.com/37118134/120035951-4a576180-bff7-11eb-941f-5162bbafa301.jpg)
![Screenshot 2021-05-28 at 7 42 28 PM](https://user-images.githubusercontent.com/37118134/120035954-4aeff800-bff7-11eb-88f0-9808202dcd48.jpg)
![Screenshot 2021-05-28 at 7 43 06 PM](https://user-images.githubusercontent.com/37118134/120035957-4cb9bb80-bff7-11eb-9449-1f948d4196a6.jpg)

## Summary 🟡

_Generally, what's your overview of the event?_

It actually went well, i say.

_How did it go for you as a Chapter Lead?_

Being the first event, seems dissapointed at the turn up today was low.

_Looking forward to the next event? What changes will you be making based on your experience from this event?_

Many things, re-shuffling my core team, making sure everyone gets active, resume our twitter page and start event awareness early.

**Comment by saintmalik** [comment]
@BolajiAyodeji  can you check into this 👀

**Comment by BolajiAyodeji** [comment]
Hi @saintmalik, thanks for the detailed report and great work on your first event!

What plans do you have to improve diversity in your future events?

Looking forward to the amazing stuff you'll do in Ado Ekiti, cheers!

**Comment by saintmalik** [comment]
> Hi @saintmalik, thanks for the detailed report and great work on your first event!
> 
> What plans do you have to improve diversity in your future events?
> 
> Looking forward to the amazing stuff you'll do in Ado Ekiti, cheers!

Already making moves and partnering with the women/girls community with campus and ado city already to get them into Open Source.

**Comment by BolajiAyodeji** [comment]
Alright, great plan and well done!
