### ISSUE TITLE
Introducing the OSCA in Mauritius | OSCAMU- 2021/06/19

### ISSUE THREAD

**Issue by GirishMahabir** [oscafrica/chapter-leads-hub#23]
## Event information
_Please complete all applicable._

- **Event name**: Introducing the OSCA in Mauritius
- **Event date**: 21/06/19
- **Event time**: 19:30 (GMT +4)
- **Event duration**: 1 Hour
- **Event location**: Online (Mauritius)
- **Estimated number of attendees**: 30 - 60

## How does this benefit your chapter?
The goal of this event is to introduce OSCA to developers and Students in Mauritius and to present them with some short words of how we will be contributing to the community.

## What help do you need with this event? 
I need help to create the form in OpenCollective.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) for sponsorship.

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created on [Open Collective](https://opencollective.com/osca).
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all related expense receipts for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Hey @GirishMahabir. Thanks for submitting this ticket. 😀

This looks good to me. Please create a registration form using [Google Forms](https://docs.google.com/forms) to keep track of the number of people who register for the event. 

Would you love us to share your event via OSCA's official social media pages? If yes, send me the necessary materials on Discord when you are ready.

We're super proud of you and your community and can't wait to see you shine.

**Comment by GirishMahabir** [comment]
Thank you @didicodes, 
Will continue the chat on Discord.

**Comment by GirishMahabir** [comment]
# POST EVENT REPORT

Hello @didicodes, 

Thank you for being the speaker in my first event for OSCA Mauritius.
We could get an amazing overview of opensource in general as well as OSCA's role.

Overall I got amazing feedback, we did expect more people but for the first time, it was great.
We now have 13 members that are willing to be part of OSCA Mauritius and I will be inviting them to our DISCORD Soon.

If I need to put more information on here, do let me know.

Thank you, 
Girish Mahabir

**Comment by BolajiAyodeji** [comment]
Hi @GirishMahabir, great work, and congratulations on your first event!

Feel free to share the feedback you got, event photos, and what you learned from organizing this event :).

Looking forward to the amazing stuff you have planned for your community, cheers!
