### ISSUE TITLE
OPEN SOURCE AND OSCA | OKENE- 2021/06/19

### ISSUE THREAD

**Issue by TressOhi** [oscafrica/chapter-leads-hub#26]
## Event information

- **Event name**: OPEN SOURCE AND OSCA
- **Event description**: An event primarily aimed at welcoming and getting to know all members of the OSCA community within this chapter; letting them know what the community is all about, and what we'll be focused on achieving in no time.
- **Event date**: _21/06/19_
- **Event time**: _10:00am (GMT +1)_
- **Event duration**: 1 hour
- **Event location**: Online (Google Meet)
- **Estimated number of attendees**:  10 to 20

## How does this benefit your chapter?
_A good number of individuals within this community have little to no idea of what Open Source is all about, so this meetup will primarily help enlighten them, and spark up their interest in Open Source._

## What help do you need with this event? 
_Nothing for now._

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Hey @TressOhi. Thanks for submitting this ticket. 😀

This looks good to me. Please create a registration form using [Google Forms](https://docs.google.com/forms) to track the number of people who register for the event.

Would you love us to share your event via OSCA's official social media pages? If yes, send me the necessary materials on Discord when you are ready.

We're super proud of you and your community and can't wait to see you shine.

**Comment by TressOhi** [comment]
Ok, thanks @didicodes

**Comment by TressOhi** [comment]
Hello, we held the meetup already but it looks like the "post-event report" link is broken.

**Comment by BolajiAyodeji** [comment]
Hi @TressOhi, apologies for that. The correct link is https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md. There was an issue in the first version of the issue template which you have used. But this issue is fixed already, but you still have the wrong link because you used the older template. I hope this helps; cheers!

**Comment by BolajiAyodeji** [comment]
Hi @TressOhi , you have not submitted your post event report yet. Kindly use the [Post Event Template](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md) and submit your report so we can review and close this issue. Thank you!

**Comment by TressOhi** [comment]
Ok, sorry I was off this long. I should submit it today.

**Comment by TressOhi** [comment]
# Post Event Report [OPEN SOURCE AND OSCA|OKENE] [2021/06/19]


## Attendance 🔵
_We had 10 people in attendance overall._

## Event Venue 🟣

_The event held on Google meet and things went well._

## The Good, Bad, and Ugly 🔴

_Everything went well, we only had to delay the start time a bit cause of late entry. _

## Event Photos 🟢

![20210717_144334](https://user-images.githubusercontent.com/47344319/126039642-e60172c1-4729-43ac-b0a4-330c05843df3.jpg)


## Summary 🟡

_The event was a success considering the kind of area in which it held._

_For me it was an awesome experience, getting to meet people actively involved and interested in Tech in my community was a pleasure._

_I'm looking forward to the next invent, hoping to grow in my journey as a chapter lead._

**Comment by BolajiAyodeji** [comment]
Hi @TressOhi, great work on your first event. We're happy to see that it went well and we look forward to more activities!
