### ISSUE TITLE
GROWING IN TECH WITH OPEN SOURCE  | AWKA - 2021/06/19

### ISSUE THREAD

**Issue by lumenCodes** [oscafrica/chapter-leads-hub#27]
## Event information
_Please complete all applicable._

- **Event name**: Growing  in tech with open source
- **Event description**: This event is will introduce people to open source, and inform them of the many benefits of contributing to open source.
- **Event date**:  21/06/19
- **Event time**: 2:30pm (GMT+1)
- **Event duration**: 1 hour
- **Event location**: Google meet (online)
- **Estimated number of attendees**: 50

## How does this benefit your chapter?
_Please let us know why we should approve this event._  

This event will serve as an introduction to the community and its goals and also get the members of the community up to speed with how they will benefit from open source. Ultimately at the end of the event members of the community are expected to be more eager and engaged in the activities of the community.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._  

Nothing for now.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [  ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by lumenCodes** [comment]
Hi, @BolajiAyodeji Please check this out.

**Comment by lumenCodes** [comment]
![OSCA! (1)](https://user-images.githubusercontent.com/60603806/120672144-f2eb4280-c489-11eb-823f-6bcdb302d83a.png)

@BolajiAyodeji This is the event flier.

**Comment by didicodes** [comment]
Hey @lumenCodes. Thanks for submitting this ticket. 😀

This looks good to me. Please create a registration form using [Google Forms](https://docs.google.com/forms) to track the number of people who register for the event.

I will send your event flier to the social media team. Can you also share the content you'd love us to share with the flier? Thanks. 

We're super proud of you and your community and can't wait to see you shine.

**Comment by lumenCodes** [comment]
Thank you so much Didi the link on the flyer leads to the registration form.

**Comment by lumenCodes** [comment]
> Thank you so much, Didi the link on the flyer leads to the registration form.

By content you mean, write-up?

**Comment by didicodes** [comment]
> By content you mean, write-up?

Yes @lumenCodes, that's what I mean. 😀

**Comment by lumenCodes** [comment]
Open source is increasing career roles in tech and It has proven to be a catalyst for exponential growth for individuals in the tech field.

Join this event organized by  Open Source Community Africa Awka and learn how open source can help you grow in your tech career as a designer, developer, writer, etc.
 Also learn how you can be able to switch career roles and contribute to open source.

**Date: Saturday, 19th June 2021.
Time: 2: 30pm WAT
Venue: Google meet.**

**Registration link is https://bit.ly/growwithos**

**Comment by didicodes** [comment]
Awesome, I will share it with our community manager. 😀

**Comment by lumenCodes** [comment]
Hi, Please I can't find the post event report. The link is throwing a 404 error.

**Comment by didicodes** [comment]
Hey @lumenCodes. Yes, there was a typo in the link. But we've updated it now. 

Find the new link [here](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md). We are looking forward to seeing your Post-event report.

**Comment by lumenCodes** [comment]
Oh Okay,
Thank you.

> Hey @lumenCodes. Yes, there was a typo in the link. But we've updated it now.
> 
> Find the new link [here](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md). We are looking forward to seeing your Post-event report.

**Comment by lumenCodes** [comment]
# Post Event Report [EVENT NAME] [DATE]
## Attendance 🔵

We had 10 persons in attendance. Sadly no female attended.

## Event Venue 🟣

The google meet call was okay there was no hitches.

## The Good, Bad, and Ugly 🔴

- The speaker was on time and also the attendees enjoyed the session.
- The google form for the registration got suspended and as result, a lot of people couldn't register.
- The mail which I sent out also received a low engagement rate
 

## TIL (Today I Learned) ⚪️

I learnt that sending mail reminders to attendees few times before the event might help.



## Summary 🟡

_Generally, what's your overview of the event?_
It was a success but can be greatly improved next time.

_How did it go for you as a Chapter Lead?_
The attendance was not encouraging but we go again next time.

_Looking forward to the next event? What changes will you be making based on your experience from this event?_

I will start on time to talk about the event and post on social media.
I will also have a plan B should incase the google form ges suspended again.

**Comment by BolajiAyodeji** [comment]
Hi @lumenCodes, thanks for the detailed report and great work on your first event!

What plans do you have to improve diversity in your future events?

Looking forward to the amazing stuff you'll do in Awka, cheers!

**Comment by lumenCodes** [comment]
So sorry for my late reply,
I will reach out to more women offline and online. I can also find a facilitator that is a female who can encourage ladies to attend because it is a lady that is speaking.
I will also know why they might not attend and try to factor it into the planning phase for my next event.
