### ISSUE TITLE
Everything Open Source | Makurdi 2021/06/26

### ISSUE THREAD

**Issue by logiquebox** [oscafrica/chapter-leads-hub#28]
## Event information
_Please complete all applicable._

- **Event name**: Everything Open Source 
- **Event description**: This event geared towards introducing the community to Every Open Source. We shall be discussing the benefits of open source, How to contribute to open source, and basically, anything related to open source
- **Event date**: 2021/06/26
- **Event time**: 3:00pm (GMT +1)
- **Event duration**: 1 hour
- **Event location**: Online (google meet)
- **Estimated number of attendees**: 50 

## How does this benefit your chapter?
This event will serve as an introduction to open source for the community members and set the pace for credible contribution to open source projects and also the benefits

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._ 
Nothing for now

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by logiquebox** [comment]
@BolajiAyodeji  please check this out

**Comment by BolajiAyodeji** [comment]
Hi @logiquebox, thanks for submitting this issue.

Your event looks good to me; great work! Please go ahead and start making the necessary arrangements.

Looking forward to your post-event report, cheers!

**Comment by logiquebox** [comment]
![OSMakurdi3](https://user-images.githubusercontent.com/37655600/121783467-ad73f700-cba6-11eb-862d-425674ca7561.png)
@BolajiAyodeji please checkout this event flier for approval.

**Comment by logiquebox** [comment]
# Post Event Report [Everything Open Source] [2021/06/26]

### Attendance 🔵
In attendance, we had a total of 10 attendees from diverse tech fields ranging from Software engineers, data scientists, and technical content writers.

### Event Venue 🟣
google meet (online) and I didn't experience any difficulty with network

The Good, Bad, and Ugly 🔴
I wouldn't say all my plans worked well because I was expecting a great number of attendees which turn out too low, but this is our first event and I have learnt some things from planing this event. 

### TIL (Today I Learned) ⚪️
I learnt that I need to create a calendar invite for my meetings, and also to work on my publicity about my event 

### Event Photos 🟢
![meet3](https://user-images.githubusercontent.com/37655600/124344634-5c668a00-dbcb-11eb-83b1-18ed462ab479.png)

### Summary 🟡
The event "Everything Open Source" was a success because the speaker did justice to the topic. And from questions raised by the attendee after the talk, shows that it was a very insightful session and I'm really looking forward to our next event.

How did it go for you as a Chapter Lead?
As a chapter leader, I would say it was quite interesting being my first virtual event and I must say that I was tense for some seconds into the event but yeah it went well for a start. And I'm really looking forward to growing the rate of credible contributions to open source from my community.

Looking forward to the next event? What changes will you be making based on your experience from this event? 
I will work on my publicity

**Comment by BolajiAyodeji** [comment]
Hi @logiquebox, great work on your first event!

Looking forward to the amazing stuff you'll do for your community, cheers!
