### ISSUE TITLE
THE POWER OF CONTRIBUTING TO OPEN SOURCE PROJECTS | KANO - 2021/06/26

### ISSUE THREAD

**Issue by bhantsi** [oscafrica/chapter-leads-hub#29]
## Event information
_Please complete all applicable._

- **Event name**: THE POWER OF CONTRIBUTING TO OPEN SOURCE PROJECTS
- **Event description**: In this event we will talk about open source in general, focusing on the advantages, opportunities, and many other aspects. Because this is our first event, we are expecting both experience and newbies developers to attend. 
- **Event date**: 2021/06/26
- **Event time**: 3:00 - 4:30  (GMT +1)
- **Event duration**: 1 HOUR 30 MINUTES
- **Event location**: VIRTUAL(google meet)
- **Estimated number of attendees**:  25 - 60

## How does this benefit your chapter?
_Please let us know why we should approve this event._
Contributing to open source gives developers plenty of advantages, benefitting their own development, in this event/meetup we will discuss what is open source, how to contribute, how to pick the right project to contribute to.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Just your approval and maybe a speaker recommendation, an industry expert

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [ ] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @bhantsi, thanks for submitting this issue.

Your event looks good to me; great work! Please go ahead and start making the necessary arrangements.

Looking forward to your post-event report, cheers!

**Comment by bhantsi** [comment]
![oskakanoevent](https://user-images.githubusercontent.com/26586086/125642601-e9307b54-06e9-4739-ad4f-b87b4fd8a027.jpg)
The event flyer

**Comment by bhantsi** [comment]
# Post Event Report [THE POWER OF CONTRIBUTING TO OPEN SOURCE PROJECTS | KANO] [2021/06/26]



## Attendance 🔵

_Attendance ranges from 9 - 16 people both male and females_

## Event Venue 🟣

_We hosted the event virtually via Google Meet and no difficulties experienced_

## The Good, Bad, and Ugly 🔴

_Everything went as planned. No issues_

 

## Social Media Highlights ⚫️
* https://twitter.com/osca_kano/status/1407638588548866048
* https://twitter.com/osca_kano/status/1408792643275046914


## Event Photos 🟢

_Screenshot from the event_
![Screenshot from 2021-06-26 15-56-14](https://user-images.githubusercontent.com/26586086/125663386-64d271d4-7c2a-41ad-a2f2-6622ce483871.png)

![Screenshot from 2021-06-26 15-39-05](https://user-images.githubusercontent.com/26586086/125661389-0da0f531-f6f7-4b96-bbe9-933b53499d8f.png)
![Screenshot from 2021-06-26 15-47-46](https://user-images.githubusercontent.com/26586086/125661428-57e64cac-5678-4b96-98fd-5d4206d2c5f9.png)
![Screenshot from 2021-06-26 15-28-52](https://user-images.githubusercontent.com/26586086/125661446-6d8e9f32-8656-40e2-b616-48e64de32362.png)
![Screenshot from 2021-06-26 15-37-14](https://user-images.githubusercontent.com/26586086/125661487-2453ef7e-6f96-409e-a98f-a2e9feb4a961.png)
![2021-06-26_15-13](https://user-images.githubusercontent.com/26586086/125661765-6072fb1f-f3e1-4ac0-9bc5-b87404ad0777.png)


## Summary 🟡

_It's amazing, especially when I realize the attendess ranges from beginners to experienced developers_

_It's a great experience, looking forward to improve_

**Comment by BolajiAyodeji** [comment]
Hi @bhantsi, great work on your first event. Keep the fire burning; we look forward to more activities!
