### ISSUE TITLE
OPEN SOURCE 101 | LUSAKA - 2021/07/03

### ISSUE THREAD

**Issue by geraldmaboshe** [oscafrica/chapter-leads-hub#37]
## Event information
_Please complete all applicable._

- **Event name**: Open Source 101
- **Event description**: In this event we will discuss what open source is, how to contribute and benefits of being involved in open source
- **Event date**: _21/07/03_
- **Event time**: _6:00 pm (GMT+2)_
- **Event duration**: 1 hour
- **Event location**: Virtual(Twitter Spaces)
- **Estimated number of attendees**: 15 - 20

## How does this benefit your chapter?
_This event would equip community members with all the knowledge they need to effectively participate in open source software_

## What help do you need with this event? 
_Nothing_

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by geraldmaboshe** [comment]
@BolajiAyodeji

**Comment by didicodes** [comment]
Hey, @geraldmaboshe. Thanks for submitting this ticket. 😀

This looks good to me. Don't forget to create a registration form using [Google Forms](https://docs.google.com/forms) or your preferred platform to track the number of people interested in participating in the event.

We're super proud of you and your community and can't wait to see you shine.

**Comment by geraldmaboshe** [comment]
# Post Event Report OPEN SOURCE 101 | LUSAKA - 2021/07/03 


## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_
16 attended. Yes, the attendance was diverse

## Event Venue 🟣
Twitter spaces


## The Good, Bad, and Ugly 🔴

Feedbaclk from the audience

 
## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._
We should have more of these

**Comment by BolajiAyodeji** [comment]
Hi @geraldmaboshe, thanks for your report. Please try to make your report more descriptive as much as you can next time. Great work on your first event!
