### ISSUE TITLE
Getting Started with Open Source|Ile-Ife - 2021/07/17

### ISSUE THREAD

**Issue by Precillieo** [oscafrica/chapter-leads-hub#39]
## Event information
_Please complete all applicable._

- **Event name**: Getting Started with Open Source
- **Event description**: Ile-Ife is a city encompassing many developers from different tech stacks. Having evaluated and estimated their capacities, we realized that many of them are aware of open source, they know they can contribute to open source in one way or the other, however, many of them don't know how to go about it, they lack the understanding of the approaches to take and how to get started even though they are passionate with all enthusiasm to dive into it. So this brought about our first event, to get them introduced to what and what are the steps to take in becoming an open-source developer.
- **Event date**: _2021/07/17_
- **Event time**: _11:00 - 12:30 (GMT+1)_
- **Event duration**: 1 HOUR 30 MINUTES
- **Event location**: Virtual (Google Meet)
- **Estimated number of attendees**: 50 - 75

## How does this benefit your chapter?
_Please let us know why we should approve this event._
Collaboration on the group right now is still a bit low due to the fact that their minds are sprinkled with small small doubts. They are all expectant of what they'd gain from being part of the community. Therefore, this first event is purposely aimed to bring togetherness among group members.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Since it is virtual. None for now. We can request during the subsequent physical ones.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [ ] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Hey, @ayoolafelix. Thanks for submitting this ticket. 😀

This looks good to me. Don't forget to create a registration form using [Google Forms](https://docs.google.com/forms) or your preferred platform to track the number of people registering for the event.

We're super proud of you and your community and can't wait to see you shine.

**Comment by Precillieo** [comment]
This is encouraging @didicodes. The Google Form will be created right away.

**Comment by Precillieo** [comment]
Post Event Report GETTING STARTED WITH OPEN SOURCE

## Attendance 🔵
A total of 33 people participated in the webinar including people from outside Ife. The event was diverse in inclusive in every sense.

## Event Venue 🟣
It was held virtually

## The Good, Bad, and Ugly 🔴
We had a great time during the meeting. The guest speaker spoke in a very basic manner such that newbies amongst us understood what Open source is all about. Although one of the challenges we faced was that during the course of the webinar, we realized that google meet now allocates time for meetings, which is about one hour. We didn’t prepare for this as we were caught unaware a few minutes to the end of the call. We did our best to quickly create a new link, but not so many people could get the link.  We made the most of our remaining time and people available to review what was been taught by the speaker and gave out gifts( #1000 worth airtime) to each of the winners from the Chapter Leads pockets. We also had a Q/A Session.

## Feedback from Attendees 🟠
During and after the event
![image](https://user-images.githubusercontent.com/62711553/128620462-bcfab0da-121e-4e0f-b6d6-3f6174058f78.png)

## Social Media Highlights ⚫️
[Ifeoluwa](https://twitter.com/thetrueerudite/status/1416346847665401867?s=20
)
[OSCAIfe](https://twitter.com/thetrueerudite/status/1416346847665401867?s=20
)

## Event Photos 🟢
[On Drive](https://drive.google.com/drive/folders/1-vDpx-1tYhvl6j_qlzeke9oKoiircqT1?usp=sharing)

## Summary 🟡
This event was a big turnaround here for us in Ile-Ife. As I wasn't really expecting the turn out to be as massive as that. I think people now believe they can amount to something and be better in their various tech stacks by being part of this OSCA Community in Ile Ife. Due to this, our next event will be physically held here in Obafemi Awolowo University Campus. Hoping it'd turn out well too.

**Comment by didicodes** [comment]
Thank you for submitting your post-event report, @Precillieo. It is really good to see people share positive feedback about the event and the community you and @ayoolafelix are building. 

Please keep up the fantastic work and let us know if there's anything we can do to make your time as a Chapter lead smoother and beneficial.
