### ISSUE TITLE
Introduction to Open Source Community Africa | Surulere-Lagos - 2021/12/10

### ISSUE THREAD

**Issue by imohweb** [oscafrica/chapter-leads-hub#41]
## Event information
_Please complete all applicable._

- Event Name: Getting Started with Open Source 

- Event Description: Surulere is a highly respectable suburb of Lagos State, Nigeria that is full of numerous persons with a background in Technology. We have identified that many of these people are interested in making contributions to the Open Source Community Africa but they do not know how to go about it. So this first event will give them a heads-up as it will help introduce them to the various approaches to take to get started with  Open Source Community Africa. In summary, this event will speak the language of Open Source Community Africa to the attendees. 

- ** Event date**: 2021/12/10
- **Event time**: 10:00 - 11:30 (GMT+1)
- **Event duration**: 1 Hour 30 Minutes
- **Event Location**: Virtual (Google Meet)
-**Estimated number of attendees**: 40 -80

##How does this benefit your chapter?
_Please let us know why we should approve this event._
The chapter is totally new in and a lot of people do not know much about open source.  Some of the people within Surulere are still in doubt if there anything like open source. Therefore, this first event is aimed at officially launching the open-source community in Surulere, pitch about collaboration, and brings about togetherness among members.

##What help do you need with this event? 
We only need help in form of publicity from Open Source Community Africa. We will like Open Source Community Africa to publicize the event on all its social media channels. 

## Checklist

**Before you post the issue**: 
- [ ] You have followed the issue title format.
- [ ] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [ ] Your event is approved.
- [ ] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Hey, @imohweb. Thanks for submitting this ticket. 😀

This looks good to me. Please create a registration form using [Google Forms](https://docs.google.com/forms) or your preferred platform to track the number of people who register for the event.

We're super proud of you and your community and can't wait to see you shine.

**Comment by imohweb** [comment]
Awesome thank you. Let me get to work asap😊

**Comment by imohweb** [comment]
hi @didicodes, 
Thanks for the opportunity to get this event started. I'm glad to inform you that the registration form for the event has been created. Here is the link to the form https://forms.gle/5c5hQNtbCQRM6K2C7. Regards

**Comment by didicodes** [comment]
This looks great, @imohweb. You can also add things like "why do you want to attend this event" or "do you have any other thing you'd love us to host in the future?" 

This will help you tailor your events to fit the needs of your community.

**Comment by imohweb** [comment]
Okay noted with thanks

**Comment by didicodes** [comment]
Oh,  I missed that. Thanks for the correction, @imohweb. 

I'm looking forward to reading about the event after it has been hosted. Have a great day. 😃

**Comment by imohweb** [comment]
Post Event Report on Introduction to/Getting Started with  Open-Source Community Africa in Surulere Lagos State Nigeria- First Meeting - 11-12-2021

## Attendance 🔵
_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_   
* We had just 6 people in attendance. All the attendees were males

## Event Venue 🟣
* The event was held Virtually via Google Meeting

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_ 
* Not really. The only difficulty I faced was with the event publicity and getting people to register and attend it.

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_  
* All the plans we had worked well. The only challenge we had was a low turnout for the event. We expected like 70+ number but only 6 people attended

_Feel free to share your positive and negative experiences here with bullet points._
* The positive experience I got was the opportunity to interact directly with the attendees. Got to know their core strength, the challenges they are facing in finding the right path to follow in tech. I was able to point them to ways they should go about it.
* The negative experience I had was a lack of support by OSCA in terms of helping retweet the event poster on Twitter despite tagging the OSCA Twitter handle. 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_  
* I learned more about how to organize and coordinate people. I also got to learn about connecting with people and sharing in their opinions. 

## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._
## Below are the Feedbacks from some of the Attendees
* It was nice meeting you guys today. Enjoy your holidays - Feedback from Richard
* Richard also suggested as a feedback that we should start training on Open Source Tools in 2022
* The event was splendid and I really learned a lot. I can't wait for another event- Feedback from Ahmed Anifowoshe
* Thank God I attended the event, it has added a lot to my knowledge - Feedback from Ibeh Kingsley

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 
* All the feedbacks were gotten after the event

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_
* Pre-event post - https://twitter.com/iamrealimoh/status/1466461187063881728
* Post-event post - https://twitter.com/iamrealimoh/status/1469961564614758404
* Pre-event Post on Facebook - https://m.facebook.com/story.php?story_fbid=1644980882499986&id=100009642692008
* Post-event Post on Facebook - https://m.facebook.com/story.php?story_fbid=1653282791669795&id=100009642692008

## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_
## Link to the Images are:
1. https://drive.google.com/file/d/1uXPiYnJm9yd6x8B3f8DPUlMoFB4NwDoS/view?usp=sharing
2. https://drive.google.com/file/d/16f5j4f2goquLu7rkrI6b2YDmCQVPwfbF/view?usp=sharing
3. https://drive.google.com/file/d/1xl-ObN1zd25M4iEMbqj3hriVZo6My_q-/view?usp=sharing

## Summary 🟡

_Generally, what's your overview of the event?_
The overall summary of the event is that it gives me and all the attendees a headstart to something great in the nearest future. 

_How did it go for you as a Chapter Lead?_
As a Chapter, the event created some level of exposure, collaboration, and leadership role for me

_Looking forward to the next event? What changes will you be making based on your experience from this event?_
* Pre-event campaign and awareness

**Comment by didicodes** [comment]
Thanks for submitting the post-event report of your recently held event. 

It's really great to see the feedback from the attendees as well. Thank you for hosting a great event @imohweb. 

Next time you submit a post-event report, please don't close the issue, either Bolaji or I will do that. Thank you and have an amazing Christmas holiday.

**Comment by imohweb** [comment]
Thank you @didicodes. Your point is well noted. Merry Christmas & a Prosperous New Year in Advance to you.
