### ISSUE TITLE
UTILIZING OPEN SOURCE AS A TOOL FOR CAREER GROWTH | NEKEDE - 2021/07/17

### ISSUE THREAD

**Issue by UdokaVrede** [oscafrica/chapter-leads-hub#42]
## Event information
_Please complete all applicable._

- **Event name**: UTILIZING OPEN SOURCE AS A TOOL FOR CAREER GROWTH
- **Event description**: What is Open Source? Why contribute to Open Source? How to contribute to Open Source?
- **Event date**: _2021/07/24_
- **Event time**: _10:00 (GMT+1)_
- **Event duration**: 1 hour 30minutes
- **Event location**: Virtual
- **Estimated number of attendees**: 25

## How does this benefit your chapter?
Being a new chapter in the community, and as the first event for a newly introduced concept, would help expose the nekede community to open Source, spread the knowledge and understanding of this concept to the community and spur their interest in Open Source.

## What help do you need with this event? 
Financial aid in form of data subscription for attendees or OSCA swags for attendees.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [x] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @UdokaVrede, thanks for submitting this issue.

Kindly make your budget link open or accept the access request so we can review your budget; thanks.

**Comment by BolajiAyodeji** [comment]
Hi @UdokaVrede, thanks for submitting this issue.

Your event looks good to me; great work! Please go ahead and start making the necessary arrangements.
Unfortunately, we cannot provide swags for your community yet, and soon we'll communicate how you should go about that.

Looking forward to your post-event report, cheers!

**Comment by UdokaVrede** [comment]
Thank you  for your response.
This means I could go ahead with disbursing data to attendees?

**Comment by BolajiAyodeji** [comment]
Yes, @UdokaVrede. We'll attend to your fund request before your event date.

**Comment by UdokaVrede** [comment]
Hi @BolajiAyodeji  sadly I couldn't host this event today as scheduled as a result of my poor health status.
However I recieved the data support in cash today from OSCA and I request that I reschedule this event till next week, Saturday 24th July 2021.

I sincerely apologize for the inconveniences in taking up this event and hope for the best in my new scheduled date.

**Comment by BolajiAyodeji** [comment]
Hi @UdokaVrede, sorry about your health once again, and thanks for letting us know.

Our apologies for sending the funds late; this was because you didn't input a bank name in your request and your unavailability to provide it. Kindly update the event date in your issue and go-ahead to host a great event!

Looking forward to your post-event report and receipts submission, cheers!

**Comment by UdokaVrede** [comment]
Thank you

**Comment by UdokaVrede** [comment]
Post Event Report UTILIZING OPEN SOURCE AS A TOOL FOR CAREER GROWTH | NEKEDE 30/07/2021


Attendance 🔵
25 people registered for the event but 9 participants joined the event, We had more males than females in attendance

Event Venue 🟣
The event was a virtual event and in the course of the event, there was a network failure from my end in the midst of my presentation however it didn't kill the spirit of the event.

The Good, Bad, and Ugly 🔴
All my plans for the event worked well except the plans of subscribing the lines of attendees some minutes before the event. This didn't work cause I tried doing it from my bank which didn't have network to process the transactions at the time.
This however is one of the result of the low turnup for the event.
Subsequently, I plan on requesting attendees to join the event and get giveaways after the event. This I think is a better way to engaging more people.

Feel free to share your positive and negative experiences here with bullet points.

TIL (Today I Learned) ⚪️
To attach links to the virtual event at the completion of a form.

Feedback from Attendees 🟠
Yes. Some attendees looked forward to having another meeting for more clarity into open source.

How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)

At the end of the event.

Event Photos 🟢
Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images

Summary 🟡
Generally, what's your overview of the event?
As an introductory event in a new chapter, the event was more of an eye opening event and attendees look forward to having more events in the future. Some of them have also joined the OSCA discord channel to collaborate more with other people.

How did it go for you as a Chapter Lead?
It was an exciting time for me, I learnt alot involved in virtual event planning through the process from the planning to execution.

Looking forward to the next event? What changes will you be making based on your experience from this event?
Subsequently, since there's just one higher institution  around Nekede, I hope to go for physical events and publicity before my next event.
Also for virtual events, I plan to add the link to the call at the end of a successful registration for the event.

**Comment by UdokaVrede** [comment]
With regards to the low turnup at the event, please @BolajiAyodeji I'd like to get information on how to make a refund for the data support sent earlier for 25 persons

**Comment by BolajiAyodeji** [comment]
Hi, @UdokaVrede,

Apologies for the delayed response and thank you for the detailed report. We're glad to see that your first event went well. Looking forward to seeing you implement all you learned from this event to your next events.

About the leftover funds, kindly submit your expense report with receipts for the amount spent and keep the remaining funds for your next event. We will deduct the amount with you from your next event. Great work!

Btw, why did you make a copy of the expense report sheets?

**Comment by UdokaVrede** [comment]
Hi @bolaji,

I made the copy of the expense report to follow the existing example.

I hope this doesn't cause any problems.


Best

**Comment by BolajiAyodeji** [comment]
Hi @UdokaVrede, you should submit your expense report directly inside the sheet. Kindly re-read the [expense guide](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) again, please.

You didn't cause any problems, kindly follow the instructions in the guide. For record sake, can you share the total you used and how much you left here while completing your report (+receipts) for expenses you made. Thank you!

**Comment by UdokaVrede** [comment]
Alright thank you.

I'd effect the changes today.
