### ISSUE TITLE
Git as an Open Source Tool | OSCA_Nairobi- 2021/07/24

### ISSUE THREAD

**Issue by veldakarimi** [oscafrica/chapter-leads-hub#46]
> Before you start, please follow the issue title format and assign yourself and your co-lead(s) to this issue.

> If the event is a multiple date event, only add the starting date in the title.

> Please note that we need **2 weeks minimum and 3 weeks maximum notice** to approve proposed events.

> Please note that we need **21 days maximum notice** to provide support from your request.

> If you don't need any support, please don't fill the request form.

> PLEASE DELETE ALL COMMENTS/QUOTES BEFORE SUBMITTING YOUR ISSUE.

## Event information
_Please complete all applicable._

- **Event name**: Git as an Open Source Tool
- **Event description**: This event will be about learning Git and how to use platforms like Github and Gitlab in Open source to promote collaboration.
- **Event date**: _21/08/14_
- **Event time**: _2pm :00_ to _4pm:00 (EAT)_
- **Event duration**: 2 hours 
- **Event location**: Youtube
- **Estimated number of attendees**:  150

## How does this benefit your chapter?
_Please let us know why we should approve this event._
This event will benefit our community in that learners will be able to:
                      -know and understand Git, 
                      - understand the importance of various platforms like Github and Gitlab,
                      - get started on contributing to open source projects 
                      
## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
You can help us by promoting our event on various platforms and attending our event to give us feedback and make our events better.

## Checklist

**Before you post the issue**: 
- [X] You have followed the issue title format.
- [X] You have applied the correct labels (Country, Type of Event, Requests).

**Before the event**: 
- [X] Your event is approved.
-  [X] Your event's RSVP page has been created.

**After the event**:  
-  [X] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
-  [ ] This issue is closed.

**Comment by didicodes** [comment]
Hey, @veldakarimi. Thanks for submitting this ticket. 😀

You ticked the "You have completed the request form (if you need sponsorship)" checklist but when I looked at the records, I didn't see any request for funds. Was this a mistake? 

Also, don't forget to create a registration form using [Google Forms](https://docs.google.com/forms) or your preferred platform to track the number of people who register for the event.

Aside from that, this event looks good to me. We will definitely attend this event as requested and create more awareness about it via our socials. I love what you and your team are doing in OSCA Nairobi. Please keep up the fantastic work.

**Comment by veldakarimi** [comment]
Hello Didi,
Yes, it was.
Currently we don't need any financial support.

Definitely, we will create means of tracking the attendees.

Thank you for the kind words.
We are aiming to make OSCA Nairobi bigger and better.

**Comment by veldakarimi** [comment]
@didicodes I have updated the changes

**Comment by didicodes** [comment]
Awesome, @veldakarimi. Event approved! 

You can go ahead and make the necessary arrangements. We are looking forward to attending the event.

**Comment by veldakarimi** [comment]
Hey @didicodes we have changed the dates of our event to 14th August. The time is still the same

**Comment by didicodes** [comment]
Alright, that's okay. Good luck with the event, @veldakarimi. 🔥

**Comment by veldakarimi** [comment]
Hello @didicodes we had a collision of our event and OSCA's event, so we had to move it once again to the 4th of September

**Comment by didicodes** [comment]
Alright, noted @veldakarimi.

**Comment by veldakarimi** [comment]
# Post Event Report [Git as An Open Source Tool] [4-09-2021]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_The attendees were really excited to join the event and they also raised a few questions to understand how they can use Git, as well as other platforms like Gitlab and Github.

## Event Venue 🟣

_We used streamyard to stream the event to Youtube, which worked fine_

## The Good, Bad, and Ugly 🔴

_We have had to postpone the event which was inconvenient since we had an event the same day OSCA was introducing its Open Source challenge.
 

## TIL (Today I Learned) ⚪️

_Today I learned that the first time to have an event is always the best._


## Feedback from Attendees 🟠

_We did not get any feedback so far.

## Social Media Highlights ⚫️

_https://twitter.com/osca_nairobi/status/1432699613652340743?s=20_
_https://www.youtube.com/watch?v=7XhVptCJI5k_

## Event Photos 🟢

_The event was live-streamed that is why we were not able to have pictures_

## Summary 🟡

_The event was good but the turnout was lower than we expected which was a disadvantage. Mainly due to the changes, we had to make._


_As a lead, the event taught me that the first time is always better than moving the event._

_Looking forward we hope to not postpone events but to hold them when they are necessary _

**Comment by didicodes** [comment]
Hi @veldakarimi, great work on this event. So sorry you had to change your event date. We're super happy about all that you and your team are doing; well done!
