### ISSUE TITLE
Introduction to Open Source for Beginners | Bauchi - 2021/08/12

### ISSUE THREAD

**Issue by sambonuruddeen** [oscafrica/chapter-leads-hub#47]
## Event information
_Please complete all applicable._

- **Event name**: Introduction to Open Source for Beginners
- **Event description**: The event is focused on beginners in the open-source ecosystem. We will begin by introducing OSCA to the attendees, then we'll talk about the open-source movement and the benefits of joining such movement. After a short break, we will move to the code lab session where each attendee will submit their first Pull Request.
- **Event date**: _2021/08/12_
- **Event time**: _11:00 am (GMT+1)_
- **Event duration**: 2 Hours
- **Event location**:  Online
- **Estimated number of attendees**: 15 - 20

## How does this benefit your chapter?
_During the event, attendees will:_

- Understand the importance of open source
- How they can get involved in the open-source movement by contributing to open source projects
- Learn what version control is and understand the basics of Git
- Get introduced to Platforms like Github and Gitlab.

## What help do you need with this event? 
_Open Source Community Africa can help with the following:_
- Event promotion
- Materials (slides, videos, etc about OSCA) for the event
- Suggestions on how to make the event better

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Hi @sambonuruddeen. Thanks for submitting this ticket. 😀

I can see that you plan to host an in-person event. However, we still don't advise you to host a physical event yet due to the ongoing COVID-19 pandemic. We believe it will be ideal for you to host a virtual event in order to keep yourself and your community safe.

Despite all said, our plans to kick-start the chapter's program was built around virtual and remote activities due to all that's happening globally, so we are not fully ready financially and resource-wise to shoulder the costs of hosting a physical event. However, we are actively working to prepare ourselves for the post-remote life when you are fully allowed to gather your community physically. Be rest assured that we will support you to host physical events when the time is right.

So, we advise making a new plan/budget to host a virtual event. Please let us know how we can support you in making your inaugural virtual event a success. Support here can include requesting an internet subscription for yourself or your community members as required. 

Do let us know if you need anything, and we'll be here to help. Cheers!

**Comment by sambonuruddeen** [comment]
I have changed the event to a virtual one. As per support for the event, I think we will require  internet subscription for some of the attendees.

Thank you for the detailed feedback.

**Comment by didicodes** [comment]
Awesome, @sambonuruddeen. Please update your budget to reflect that changes. 

As soon as you do, let me know, and I will approve the event. Thanks 😃

**Comment by sambonuruddeen** [comment]
Hi @didicodes.  I have updated the budget as requested.

**Comment by didicodes** [comment]
Awesome, @sambonuruddeen. Please go ahead and start planning for the event. 

We are looking forward to seeing what you come up with.  😃

**Comment by didicodes** [comment]
Hey, @sambonuruddeen. The funds for your event have been sent to your account. After you've completed your event, we expect to see proof (e.g. screenshots, receipts) of how the money was being spent so we can revert back to our financial team. 

Thank you very much for all you've done so far. We are looking forward to the amazing things you will do within your community and Africa at large.

**Comment by sambonuruddeen** [comment]
# Post Event Report [Introduction to Open Source for Beginners | Bauchi] - [2021/08/12]

## Attendance 🔵

We had a total of 15 attendees who joined our call. The attendees were majority male with only 3 females.

## The Good, Bad, and Ugly 🔴

_The event went as planned without a hitch, thanks to,  surprisingly, a stable network. The only problem I had was that I couldn't take a screenshot with all attendees in view because I was not on my usual computer._

## TIL (Today I Learned) ⚪️

_There is a growing interest in the Open Source Movement here in Bauchi and with a bit of work, it can grow._


## Feedback from Attendees 🟠

_The feedbacks received were unanimously positive, with suggestions about how to make our subsequent events better_

_The feedbacks were received during the Q&A Session at the end of the Event._


## Event Photos 🟢

[Image](https://photos.app.goo.gl/E5w7XPPdm1nBPvrr8)

## Summary 🟡

_The event was a huge success_

_I enjoyed every bit of the event and I'm encouraged by the enthusiasm of the attendees to learn, especially when talking about Git & Github_

_Hopefully, the next event will be a physical one so that we can have an immersive and highly interactive Codelab Session_

**Comment by didicodes** [comment]
> The event went as planned without a hitch, thanks to, surprisingly, a stable network.
Haha, nice. I'm glad the internet connection wasn't a blocker. 

Please do well to take a screenshot of your events next time it is very important for us to use it to prove that you actually hosted an effect. 

Thank you so much for hosting a fantastic event. Do have an amazing week and let us know if there's anything we can do to make this journey smoother for you.  @sambonuruddeen
