### ISSUE TITLE
OPEN SOURCE 101 | Eldoret - 2021/07/23

### ISSUE THREAD

**Issue by jamesaduke** [oscafrica/chapter-leads-hub#49]
- **Event name**: OPEN SOURCE 101
- **Event description**: Introducing members to open source and the opportunities it entails
- **Event date**: 21/07/31
- **Event time**: 4:00pm to 6:00pm(EAT)_
- **Event duration**: 2 hours
- **Event location**: Virtual
- **Estimated number of attendees**: 10

## How does this benefit your chapter?
Introducing people to open source and some of the opportunities it entails
## What help do you need with this event? 
 @

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by jamesaduke** [comment]
I am unable to assign a label or assignees

**Comment by BolajiAyodeji** [comment]
Hi @jamesaduke,

You can't assign labels yet because you've not accepted the request to join the OSCA organization on GitHub. However, once you do that, you should be able to add labels and assignees. Kindly check your email for the invite.

Your event looks good to me; great work! Please go ahead and start making the necessary arrangements.
Looking forward to your post-event report, cheers!

**Comment by jamesaduke** [comment]
Hey,
The speaker postpone in the last minute so i had to postpone and find another speaker

**Comment by BolajiAyodeji** [comment]
> Hey,
> The speaker postpone in the last minute so i had to postpone and find another speaker

Hi @jamesaduke, that's fine. Kindly update your issue to reflect this change; thanks!

**Comment by jamesaduke** [comment]
# Post Event Report [OPEN SOURCE 101 - INTRODUCTION TO OPEN SOURCE] [31ST JULY 2021]
## Attendance 🔵
The attendance was about 5 people.
It was attended by mostly university students

## Event Venue 🟣
I livestreamed the event on youtube using streamyard  so the attendance there were no technical issues. 

## The Good, Bad, and Ugly 🔴

Unfortunately i had issues with my internet connection and the speaker so there were some breaks during the event
I tried to RSVP using google forms and it did not go as smoothly as i expected. 

## TIL (Today I Learned) ⚪️

I realised how challenging organizing any event and how planning has to be done way ahead of time 

## Feedback from Attendees 🟠

No there was no feedback

## Social Media Highlights ⚫️

https://twitter.com/oscaeldoret/status/1419683715928805382

## Summary 🟡
I cannot wait to host the  next event and hopefully with more attendees . The speaker had a good presentation that was easily understood . It went well enough but not to my expectations as a Chapter Lead. For the next event i would increase the notice time for the next event for proper planning and also enough time to get the word out.
I would like for the next time to use google meet or zoom to make the session more interactive.

**Comment by BolajiAyodeji** [comment]
Hi @jamesaduke, thanks for the detailed report. I'm glad you have identified points for improvement and we can't wait to see you go stronger. Great work on your first event!
