### ISSUE TITLE
GIT AND GITHUB AS AN OPEN SOURCE TOOL  | ADO EKITI - 2021/08/19

### ISSUE THREAD

**Issue by saintmalik** [oscafrica/chapter-leads-hub#51]
## Event information
_Please complete all applicable._

- **Event name**: GIT AND GITHUB AS AN OPEN SOURCE TOOL
- **Event description**: This event will be about learning how to use GitHub, Gitlab and Git to contribute to Open Source and to promote collaboration amidst members regardless of their location.
- **Event date**: 2021/08/19
- **Event time**: 5:00 pm (WAT)
- **Event duration**: 3 hours
- **Event location**: Google Meet
- **Estimated number of attendees**: 30 - 80

## How does this benefit your chapter?
_Please let us know why we should approve this event._
- Learn how to use Github and Gitlab tool.
- how they can kickstart their contribution to open source projects.
- How to make pull requests.
## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Through promoting our event on various platforms and attending our event to provide feedbacks about our event will do.

## Checklist

**Before you post the issue**: 
- [X] You have followed the issue title format.
- [X] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [ ] Your event is approved.
- [ ] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Hey @saintmalik. Event approved!

You can go ahead and make the necessary arrangements. We are looking forward to attending the event.

**Comment by saintmalik** [comment]
> Hey @saintmalik. Event approved!
> 
> You can go ahead and make the necessary arrangements. We are looking forward to attending the event.

Thanks

**Comment by saintmalik** [comment]
Here is our flier, will be glad if you guys help us share it😌

**Comment by saintmalik** [comment]
# Post Event Report [GIT AND GITHUB AS AN OPEN SOURCE TOOL | OSCA ADO EKITI] [2021/08/19]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_

Yeah, attendances ranges between 1-13, also, both genders attended the event

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_

It was totally online, Google Meet and was recorded also

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_

_Feel free to share your positive and negative experiences here with bullet points._

- While reocrding the session, i made a silly mistake by using my earpiece forgetting that the scrreen record uses my system default speaker for voice in the screen record
- Few people came compare to the number of signups and group member.
- Yeah the little people who turned up were responsive.
- Also happy i made some impact even if the members attending the event wasnt as much as expected.
 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_

- Getting people to speak at my event
- How to use Git and Github
- Contributing to opn source project through issues
- How to contribute and create Pull request using Git and Manually via GitHub

## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._

Yes, WhatsApp Feedback from a member 
![Screenshot 2021-08-20 at 1 18 58 PM](https://user-images.githubusercontent.com/37118134/130232095-b5572ca8-dc56-475e-9e24-779ae9e83b26.jpg)


*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_


## Event Photos 🟢
![Screenshot 2021-08-19 at 5 59 57 PM](https://user-images.githubusercontent.com/37118134/130655149-6f9d7a81-18ef-4053-aef8-b3e676ae679c.jpg)
![Screenshot 2021-08-24 at 5 35 25 PM](https://user-images.githubusercontent.com/37118134/130655467-e5b37623-a5d1-43e3-94a3-2a611516a66c.jpg)
![Screenshot 2021-08-24 at 5 35 35 PM](https://user-images.githubusercontent.com/37118134/130655495-b3356080-56e4-4fc5-86c5-f45dbc5aaa7f.jpg)
![Screenshot 2021-08-24 at 5 35 50 PM](https://user-images.githubusercontent.com/37118134/130655504-cbde99b6-6e0b-4eb8-99ad-340bf8fc5581.jpg)
![Screenshot 2021-08-24 at 5 36 08 PM](https://user-images.githubusercontent.com/37118134/130655511-2e395e5f-3f37-497d-baa0-501c1bbe3b10.jpg)
![Screenshot 2021-08-24 at 5 36 28 PM](https://user-images.githubusercontent.com/37118134/130655516-31e62094-d7e8-4934-8aa9-1381447b1438.jpg)
![Screenshot 2021-08-19 at 5 33 51 PM](https://user-images.githubusercontent.com/37118134/130654933-af898061-e188-4219-9621-fd6c0dabde11.jpg)
![Screenshot 2021-08-19 at 5 34 51 PM](https://user-images.githubusercontent.com/37118134/130654938-6c6a8464-8def-4475-b216-c24626895cb4.jpg)
![Screenshot 2021-08-19 at 5 37 36 PM](https://user-images.githubusercontent.com/37118134/130654951-3816f843-d560-4512-b5da-603ceb58c65e.jpg)

## Summary 🟡

_Generally, what's your overview of the event?_

It actually went well.

_How did it go for you as a Chapter Lead?_

The turn up today was very low compared to attendees and registration, felt very disappointed at the fact that not all member knows how to use github and yet they didn't show up for the session.

_Looking forward to the next event? What changes will you be making based on your experience from this event?_

Making sure active members who wants to learn increase, resuming our twitter page.

**Comment by didicodes** [comment]
This was very interesting to read. I am glad the event turned out well regardless of the number of people that attended the event. 

It's also great to see the comment from that person who sent it a pull request. Thank you for the amazing contributions you are making to spread the word about Open Source in your community. We really appreciate it. Keep up the good work, @saintmalik.

**Comment by saintmalik** [comment]
> This was very interesting to read. I am glad the event turned out well regardless of the number of people that attended the event.
> 
> It's also great to see the comment from that person who sent it a pull request. Thank you for the amazing contributions you are making to spread the word about Open Source in your community. We really appreciate it. Keep up the good work, @saintmalik.

Thank you
