### ISSUE TITLE
HOW DO I GET INTO THE  OUTREACHY INTERNSHIP | OSCA_NEKEDE - 2021/10/01

### ISSUE THREAD

**Issue by UdokaVrede** [oscafrica/chapter-leads-hub#53]
- **Event name**:  HOW DO I GET INTO THE  OUTREACHY INTERNSHIP
- **Event description**: This event is to introduce and expose the members of the OSCA NEKEDE community to open source internships and give them tips on how to apply to open source internships.Outreachy would be the theme internship to be discussed.
- **Event date**: _2021/10/01_
- **Event time**: _04:00pm - 05:00pm_
- **Event duration**: 1hour
- **Event location**: Google Meet
- **Estimated number of attendees**: 20

## How does this benefit your chapter?
This program would help members of my community in making successful applications and contributions to getting accepted into the outreachy internship.

## What help do you need with this event? 
Funds for Data Subscription for the guest speaker, and attendees.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
This is a very interesting topic and I strongly believe your community members will benefit from it. Event approved, @UdokaVrede! 

Please go ahead and make the necessary arrangements for the event.

**Comment by UdokaVrede** [comment]
Thank you very much Edidiong,

Best Regards,

Udokaku Ugochukwu

**Comment by didicodes** [comment]
Yes, that's perfect @UdokaVrede. I'm looking forward to reading your post-event report about the event.

**Comment by UdokaVrede** [comment]
# Post Event Report How DO I GET INTO THE OUTREACHY INTERNSHIP | OSCA_NEKEDE


## Attendance 🔵

-  There were more females than males at the event. Out of the 9 persons in attendance, 5 were females and the other 4 were males

## Event Venue 🟣

Google Meet

## The Good, Bad, and Ugly 🔴

The plans around the order of the event went well and as planned but plans around the number of attendees was below expectation although after the event I got mail, chat and call notification from some attendees up to 7 persons that experienced difficulty joining for different reasons like; poor connection, forgetting the event time, inability to join the meeting.

_Feel free to share your positive and negative experiences here with bullet points._
#### POSITIVE 
- The attendees communicated efficiently and were very express with their area of confusion on the subject matter.
- After the event some attendees reached out for further help reviewing their essays which I did.
- The attendees and guest speaker really enjoyed the session.

#### NEGATIVE
- Low turnout of attendees
- Attendees unable to join
- I did not share a feedback form link
 

## TIL (Today I Learned) ⚪️

I learnt to always provide answers to people's need once identified. When the thought of this event crossed my mind, I expected that the event would be more of an expository event to what outreachy is but in the course of the event, I noticed most of the attendees where applicants having difficulty who needed help with clarifications. 


## Feedback from Attendees 🟠

 After the event.

**Comment by UdokaVrede** [comment]
Hi @didicodes again I did not use up the funds I have with me from OSCA.

Though I plan on organizing another event soon, I would like to return the balance, I think it might come handy for another chapter lead ----- _just my thoughts tho'_

Also, I am still finding it difficult sending in my post event report,I and Bolaij planned on sorting this out but we've been having conflicting schedules. Please if you would be available over the weekend (Saturday or Sunday), I would like that we schedule a meeting between 5-7pm for this.

Kind Regards!

**Comment by didicodes** [comment]
Hi @UdokaVrede, great work on this event. We're super happy about all that you are doing; well done!

**Comment by BolajiAyodeji** [comment]
> Hi @didicodes again I did not use up the funds I have with me from OSCA.
> 
> Though I plan on organizing another event soon, I would like to return the balance, I think it might come handy for another chapter lead ----- _just my thoughts tho'_
> 
> Also, I am still finding it difficult sending in my post event report,I and Bolaij planned on sorting this out but we've been having conflicting schedules. Please if you would be available over the weekend (Saturday or Sunday), I would like that we schedule a meeting between 5-7pm for this.
> 
> Kind Regards!

Hi @UdokaVrede, let's talk on Discord to finalize your receipts issues. You should still hold onto the balance with you once you submit your financial report. We'll discuss more on this in the meeting; great work!
