### ISSUE TITLE
OPEN SOURCE IN MACHINE LEARNING | KAMPALA - 2021/10/14

### ISSUE THREAD

**Issue by KakoozaJerry** [oscafrica/chapter-leads-hub#54]
## Event information

- **Event name**: Open Source in Machine Learning
- **Event description**: We will be xploring the various ways one can contribute to Open Source ML Based Projects
- **Event date**: 2021/10/14
- **Event time**: _6:00 PM (GMT +3)_
- **Event duration**: 2 HOURS
- **Event location**: ZOOM
- **Estimated number of attendees**:  60

## How does this benefit your chapter?
_As many people are trying to explore the various opportunities  available in Open Source , there is not much Knowledge of open source machine learning project and yet they do exist. This session is to provide real world examples of ML Bases open source projects and how one can get involved_

## What help do you need with this event? 
_Funds._

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @KakoozaJerry, thanks for submitting this issue.

Your event looks good to me; great work! Please go ahead and start making the necessary arrangements. We will get back to you soon with regards to the sponsorship requested.

Looking forward to your post-event report, cheers!

**Comment by KakoozaJerry** [comment]
Okay @BolajiAyodeji  , thanks for the feedback.  Let's make the necessary arrangements for it.

**Comment by KakoozaJerry** [comment]
@BolajiAyodeji , The RSVP links have been created and people are registering 

https://bit.ly/OSCA-Kampala-03-1
https://bit.ly/OSCA-Kampala-03-2

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji , The RSVP links have been created and people are registering
> 
> https://bit.ly/OSCA-Kampala-03-1 https://bit.ly/OSCA-Kampala-03-2

Yayyy! Well done @KakoozaJerry!

**Comment by BolajiAyodeji** [comment]
Hi @KakoozaJerry, we're happy to see that your event went well. Great work, and keep going!

Next time, please take out questions from the event report template if you don't need them before submitting them. But, again, the template is a guide, and you don't have to use every part, so only use the sections you want and remove the rest. Cheers!
