### ISSUE TITLE
deepEnd with GitHub Actions | OSCANairobi - 2021/11/20

### ISSUE THREAD

**Issue by TabithaKavyu** [oscafrica/chapter-leads-hub#60]
## Event information
_Please complete all applicable._

- **Event name**: deepEnd with GitHub Actions
- **Event description**: The event is meant to dive into GitHub Actions, including core concepts and essential terminology.
- **Event date**: _2021/11/20_
- **Event time**: _2:00pm - 3:30pm (EAT)_
- **Event duration**: 1 hour 30 minutes
- **Event location**: Online
- **Estimated number of attendees**: 50

## How does this benefit your chapter?
_The key to timely and safe software development and updates is automation.This event  will help our community members use GitHub Actions to  accelerate their application development workflows by creating custom Software Development Life Cycle workflows in their GitHub repositories._

## What help do you need with this event? 
_Help us promote the event online._

## Checklist

**Before you post the issue**: 
- [ ] You have followed the issue title format.
- [ ] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [ ] Your event is approved.
- [ ] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Hi @veldakarimi, thanks for submitting your event request. Your event is approved and you can go ahead to begin planning. Thank you for all you've done so far. Do let us know how this event goes; cheers!

**Comment by veldakarimi** [comment]
Post Event Report [deepEnd With Github Actions]  [2021/11/20]


## Attendance 🔵

_The audience had people from diverse backgrounds from different countries as well as different tech stacks_   

## Event Venue 🟣

_The event was online and we did not experience any challenges_ 


## The Good, Bad, and Ugly 🔴

_The plan in terms of marketing strategy, was spot on. The event was online so in terms of budgeting we did not require funds_  


_The event was okay, the speaker showed up on time but we had 18 attendees which were lower than anticipated. We realized that we had set it up close to the public holiday here. Nevertheless, the event was recorded for future reference_


## TIL (Today I Learned) ⚪️

_During holidays try not to have an event at that time_  



## Summary 🟡

_The event was informative and engaging which was good. _

_So far so good. I could not complain_

_Changes to be made was to watch out on having events close to holidays _

**Comment by BolajiAyodeji** [comment]
Hi @veldakarimi, thanks for sharing your report! We're glad your event went well, and you learned something new. Keep it up!
