### ISSUE TITLE
LEVERAGING COMMUNITY FOR A BETTER TECH INDUSTRY | KAMPALA CHAPTER - 2021/11/25

### ISSUE THREAD

**Issue by KakoozaJerry** [oscafrica/chapter-leads-hub#61]
## Event information
_Please complete all applicable._

- **Event name**: Leveraging Community for a better Tech Industry
- **Event description**:
- **Event date**: _25/11/2021_
- **Event time**: _3:00 PM (EAT)_
- **Event duration**:  1 HOUR
- **Event location**: Virtual
- **Estimated number of attendees**: 60

## How does this benefit your chapter?
_The community will  be able to make use of the power of the community to tap into resources and the vast amount of opportunities and mentorship they may gain._

## What help do you need with this event? 
_Financial._

## Checklist

- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [ ] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @KakoozaJerry,

Thanks for submitting your event request. Your event looks good to me and is approved (but without $ support as discussed); great work! Please go ahead and start making the necessary arrangements. 

Looking forward to your post-event report, cheers!

**Comment by KakoozaJerry** [comment]
@BolajiAyodeji , The event happened and was successful.

Great turn up of individuals and the community loved it.

Was able to post the session on the chapter youtube channel

**Comment by BolajiAyodeji** [comment]
Great work @KakoozaJerry!
