### ISSUE TITLE
Women TechMakers Kano Power Panel | OSCA-KANO - 2021/11/27

### ISSUE THREAD

**Issue by bhantsi** [oscafrica/chapter-leads-hub#62]
## Event information

- **Event name**: WTM Kano Power Panel
- **Event description**: This event is a collaboration between OSCA Kano and Women TechMaker Kano. The SSA Power panel campaigns are panel sessions with the aim of hosting accomplished women in tech and highlighting their success stories within their regional communities, while also sharing tips on how women will engage in open-source.

- **Event date**: _2021/11/27_
- **Event time**: _10:00 A.M (GMT +1)_
- **Event duration**: 4 hours
- **Event location**: CIT Theater  Bayero University Kano (New Campus)
- **Estimated number of attendees**:  100

## How does this benefit your chapter?
_This event will introduce the open-source project, community, and engage women tech-makers into women in OSS_

## What help do you need with this event? 
Approve this event, some funding, and swags(T-shirts and stickers) to make it a success.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by bhantsi** [comment]
@didicodes @BolajiAyodeji

**Comment by BolajiAyodeji** [comment]
Hi @bhantsi,

Thanks for submitting your event request. Your event looks good to me; great work! Please go ahead and start making the necessary arrangements. We'll get to you soon with regards your sponsorship request.

Looking forward to your post-event report, cheers!

**Comment by BolajiAyodeji** [comment]
@bhantsi, please remember that you don't need to "tag us" here after opening an issue; we always get notified once you get an issue, and we'll attend to it soon.

**Comment by bhantsi** [comment]
> @bhantsi, please remember that you don't need to "tag us" here after opening an issue; we always get notified once you get an issue, and we'll attend to it soon.

Ok

**Comment by bhantsi** [comment]
Here is the event RSVP https://gdg.community.dev/events/details/google-gdg-kano-presents-wtm-kano-power-panel/

**Comment by bhantsi** [comment]
# Post Event Report  **[ Women TechMakers Kano Power Panel | 2021/11/27 ]**

## Attendance 🔵

_Most of the attendees were women because the event was targeted towards women, although we have male attendees as well, we have approximately 73 people_

## Event Venue 🟣

_The event venue was easy to locate and is convenient for the event_

## The Good, Bad, and Ugly 🔴

_Althogh we budget for 100+ attendees and pay for their light refreshment in advance, only to end up having less than what we are expected, therefore we end up having some leftover refreshments_

## Event Photos 🟢
![WhatsApp Image 2021-12-11 at 21 37 05](https://user-images.githubusercontent.com/26586086/147385908-6ec4adcf-b6fc-4408-8c04-fb10f737a8bc.jpeg)
![WhatsApp Image 2021-12-11 at 21 37 05 (1)](https://user-images.githubusercontent.com/26586086/147385912-0c96cb3b-3a89-4fe5-bf28-8c98cf9cbc06.jpeg)
![WhatsApp Image 2021-12-11 at 21 37 05 (2)](https://user-images.githubusercontent.com/26586086/147385916-936dea47-e8cb-4527-8ec0-1560bd0e353e.jpeg)
![WhatsApp Image 2021-12-11 at 21 37 05 (7)](https://user-images.githubusercontent.com/26586086/147385927-47bca8b2-5bf7-4ec4-b739-6b66c4ed1923.jpeg)
![WhatsApp Image 2021-12-11 at 21 37 05 (6)](https://user-images.githubusercontent.com/26586086/147385934-e7ac5a34-3136-47ad-8d7d-8190df9aa2d8.jpeg)
![WhatsApp Image 2021-12-11 at 21 37 05 (8)](https://user-images.githubusercontent.com/26586086/147385942-2871c676-8c82-46e0-b1c7-16e2f3c13c53.jpeg)
![WhatsApp Image 2021-12-11 at 21 37 05 (4)](https://user-images.githubusercontent.com/26586086/147385949-e01d5d8f-7613-4513-a4b9-a3ae83941eb9.jpeg)



## Summary 🟡


_It was awesome collaborating with other tech communities to share and learn amazing things, networked, and came with some innovative ideas. Most importantly, engaging more women into open-source community_

_Will try as much as we can to know the exact number of my attendees so that we will not over budget on refreshment and so on_

**Comment by BolajiAyodeji** [comment]
Hi @bhantsi, thanks for sharing your report.

We're excited to see that your event and collaboration went well; great work!
