### ISSUE TITLE
BEST PRACTICES FOR OPEN SOURCE CONTRIBUTION AND MAINTENANCE | LUSAKA - 2021/12/04

### ISSUE THREAD

**Issue by geraldmaboshe** [oscafrica/chapter-leads-hub#63]
## Event information

- **Event name**: Open Source Best Practices
- **Event description**: This is an event meant to provide information about best practices in open source contributions
- **Event date**: _21/12/04_
- **Event time**: _6:00pm CAT_
- **Event duration**: 1 hr
- **Event location**: Twitter spaces
- **Estimated number of attendees**: 20

## How does this benefit your chapter?
_This will enlighten the chapter members of how to go about their open source journey_

## What help do you need with this event? 
_Non_

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [ ] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [x] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @geraldmaboshe,

Thanks for submitting your event request. Your event looks good to me; great work! Please go ahead and start making the necessary arrangements.

Looking forward to your post-event report, cheers!

**Comment by geraldmaboshe** [comment]
# Post Event Report [BEST PRACTICES FOR OPEN SOURCE CONTRIBUTION AND MAINTENANCE] [2021/12/04


## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_
11 people attended, which was quite low compared to what we expected.  

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_
The event venue was just okay

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_
All worked well, we just need to advertise the event more next time

## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._
Yes, they wanted to see more local open source projects

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 
During the event

## Summary 🟡

_Generally, what's your overview of the event?_
It was great

_How did it go for you as a Chapter Lead?_
It went well. I just hope my request to add a Co-Lead would be approved soon

_Looking forward to the next event? What changes will you be making based on your experience from this event?_
I will advertise the event more to increase on the attendance

**Comment by BolajiAyodeji** [comment]
Hi @geraldmaboshe, thanks for sharing your report! We're glad your event went well, and you learned something new. Keep it up! Yes, we're reviewing your request for a co-lead and will get to you soon :).

Next time you submit a post-event report, please don't close the issue; either Edidiong or I will do that. Thank you, and have a fantastic Christmas holiday.
