### ISSUE TITLE
ADVANCE YOUR CAREER WITH OPEN SOURCE AND END OF THE YEAR MEETUP | OSCA IKOT-EKPENE - 2021/12/30

### ISSUE THREAD

**Issue by favourmark05** [oscafrica/chapter-leads-hub#65]
> Before you start, please follow the issue title format and assign yourself and your co-lead(s) to this issue.

> If the event is a multiple date event, only add the starting date in the title.

> Please note that we need **2 weeks minimum and 3 weeks maximum notice** to approve proposed events.

> Please note that we need **21 days maximum notice** to provide support from your request.

> If you don't need any kind of support, please don't fill the request form.

> PLEASE DELETE ALL COMMENTS/QUOTES BEFORE SUBMITTING YOUR ISSUE.

## Event information
_Please complete all applicable._

- **Event name**: ADVANCE YOUR CAREER WITH OPEN SOURCE
- **Event description**:
- **Event date**: 2021/12/22
- **Event time**: 11AM - 2PM
- **Event duration**:
- **Event location**: IKOT-EKPENE
- **Estimated number of attendees**: 100

## How does this benefit your chapter?
_Please let us know why we should approve this event._
The event is aimed at promoting awareness and harnessing impactful collaborations amongst tech enthusiasts. Participants would learn about various open-source projects one can contribute to, thus, creating an impact on the technologies they use daily. Understand and utilize the benefits derived from collaboration on large scale projects which definitely could serve as a highlight in an individuals’ resume preparation. Lastly, how persons without core technical backgrounds can contribute and create impact in open source projects. The virtual event is proposed to span within one hour thirty minutes (1hr 30mins), to be held on 18 November 2021. The highlights include:
1.     Making first contributions
2.     Open source for technical and non-technical contributors
3.     Starting/creating an open-source project.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Open Source Community Africa will be of help with financial support and Open Source Swags (if possible)

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.

- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x]  Your event is approved.

- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [x] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by favourmark05** [comment]
@didicodes @BolajiAyodeji

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05,

Thanks for submitting your event request. Your event looks good to me; great work! As earlier mentioned in the last community call, we can't sponsor physical events yet due to our low budget. We'll be happy to sponsor your event if the cost is around the same amount we spend on virtual events. Would you please update your budget or let us know how you'd like to proceed?

Btw your budget is suitable and sufficient; well done. We're just not capable at the moment of covering it all. Your understanding is appreciated.

**Comment by BolajiAyodeji** [comment]
> @didicodes @BolajiAyodeji

Also, remember that you don't need to "tag us" after opening an issue; we always get notified once you get an issue, and we'll attend to it soon 🙃.

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji ,

Sorry for Responding this late, I had to meet with my core team members and see a possible solution or alternative for this event. having met with them and weighing all options we have decided not to hold a virtual event as it will have zero to no impact on our community seeing the fact that most of them are new to tech and may not embrace the importance of a virtual meetup.

kind regards,
Mfonido Mark
OSCA Lead Ikot-Ekpene.

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, that's fine then. As earlier mentioned we'll be happy to sponsor your event if the cost is around the same amount we spend on virtual events. Would you please update your budget by reducing the amount to the base cost of an average virtual event?

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji,
I think I have an issue really knowing the estimated budget for virtual and physical events for OSCA chapters, Please I will love it if you can point me to the guidelines for it.

Thanks.

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05.

So generally virtual event costs cover for internet and other prizes mainly which is usually below 100k for medium-sized events and <= 50k for smaller-sized events. We don't have any estimate for physical events yet, as mentioned we have no plans for it until next year. Do let me know if this helps, thank you.

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji ,
Thanks for the heads up, I did meet with my team members, and we have decided to give it a try for the virtual event and also use that day to round up all of our events for 2021, I have made an adjustment to the budget and this is the link to the new budget https://docs.google.com/document/d/1YHRrbPuyfTSEhebQOr32uU2rtmd1mXOoAsKFczZsVKo/edit?usp=sharing and also the date for the event has been scheduled for 28 December 2021, because of this festive season. 
and also the theme has been changed to "ADVANCE YOUR CAREER WITH OPEN SOURCE AND END OF THE YEAR MEETUP", will be expecting your kind and positive response to seeing this event a success.

Thanks,
Mfonido Mark
OSCA IKOT-EKPENE

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05,

Thanks for the update. What does "DESIGNS, DATA FOR SOCIAL MEDIA HANDLERS AND PUBLICITY" mean, please?

For the sake of a budget, you should define the items of an "honorarium" and not just put it out attached with a cost. Are you paying your speaker's cash to come to speak at your event? Honorarium should be the last thing you would want to spend money on for a local virtual event but if you want to that's fine too. I only suggest that you're clear about the content of the honorarium just as you did with adding "data" for speakers.

Do let me know about my inquiries above and once we come to a conclusion, your event will be approved. Thank you!

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji ,
I have updated the budget and made it clearer, please do check it out.

Thanks.

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, why are you paying for designs? This is something you should do in-house in your community. Also, why are you paying for data for social media publicity data  (which is even higher than the event data) when you already have data budgeted for the event itself?

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji ,
I went through your response and here is the breakdown of each item you marked out.
We have volunteers but to avoid excuses, we need to give a stipend for the three accounts. Facebook, Twitter, and LinkedIn. We initially wanted to add Instagram but seeing that we don't have a functional Instagram account, we've decided to leave it out. For the designs, we have someone who usually does free designs for the community, but she's not available at this period to help with the event, and every other good designer is busy but a few are willing to offer their services at a subsidized rate, which is why we have to pay for the designs.

Please do check the Budget again for a review, it has been adjusted.

Thanks,
Mfonido Mark.

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji ,
Greetings I am still expecting your response.

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, apologies for the delays.

Regarding your last feedback:

In the spirit of cutting costs and making sure we're minimal as much as possible, we think it's pretty excessive to spend 9k NGN on internet for "social media" publicity for this event. We will proceed to approve your budget without that, please. Kindly update your budget to reflect this change, and good luck with your event 😉!

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji ,

Thanks for your feedback, necessary update has been effected on the budget as requested, please do confirm if it is okay now.

Thanks.

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, the approved funds have been disbursed! Good luck with your event and we look forward to your post-event report.

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji ,
Thanks alot, the funds was well received

**Comment by favourmark05** [comment]
# Post Event Report [ADVANCE YOUR CAREER WITH OPEN SOURCE AND END OF THE YEAR MEETUP] [30-12-2021]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_
The total number of people that attended the virtual event was 58, 42 male and 16 females. majority of them are students and professional software developers.

## Event Venue 🟣
_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_
The event was virtual and was hosted on Google meet. there were no serious issues from our end because we tested the platform a day before the day of the event, the only issues we saw were issues from our participants who to them was the first time using google meet.

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_
All the plans for the events went as planned

_Feel free to share your positive and negative experiences here with bullet points._
 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_
I learnt that always do not try to do all things concerning a community all by yourself, delicate responsibilities to your team members and trust that they will deliver.

this is one of the many good reasons why this event came out successfully 


## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._
Yes a lot of them did give feedback about this event during the end of the event, they appreciated the opportunity OSCA Ikot-Ekpene gave them to attend and learn from the event.

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 
During the event and personally through DM's

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform

https://twitter.com/b_hantsi/status/1476631570823925773?t=cWX0oro-xsrjUK1VHbCmyA&s=19
https://twitter.com/saintmalik_/status/1476625375400706053?t=ZT-OnlYkOHZttKfukDV1PQ&s=19
https://twitter.com/EkanemEvidence/status/1476516401104171009?t=EeYVvJOTbhakaqWv_Lhkxw&s=19
https://twitter.com/Bullion_Eddie/status/1476513413010493445?t=2-59M0orxh159XUtwYQqMA&s=19
https://twitter.com/b_hantsi/status/1476499392349749255?t=PyEYP-DOHjmrMJgr3lLi2Q&s=19
https://twitter.com/oscaIK/status/1476261177978245131?t=r2QNKsSWGH9kskGoqJX-DA&s=19


## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_
https://drive.google.com/drive/folders/1XEL8C5tASfUBd78Pr8_D-PV7LTuMKDRg?usp=sharing

## Financial Report 🟡
I really appreciate OSCA Africa for the financial support for this event, it really went a long way to see the success of this event.
https://drive.google.com/drive/folders/1zZ94Tcy4Kmn69mBW35xNBknOC6XkiygV?usp=sharing
Attached above is the Payment Receipt for how the financial support was been used, Data support (giveaways were given to 10 persons) and N5000 was sent to the moderator of the event for Data Support.

## Summary 🟡

_Generally, what's your overview of the event?_
It was successful and the purpose of the event was achieved.

_How did it go for you as a Chapter Lead?_
it gave me more experience as a chapter lead, in organizing and working with a team to see the success of an event

_Looking forward to the next event? What changes will you be making based on your experience from this event?_
for now, nothing at all is to be changed.

@BolajiAyodeji 

Thanks,
Mfonido Mark
OSCA LEAD IKOT-EKPENE

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji ,

Good Evening, still expecting a review of the post-event report for my last event, so that this issue can be closed.

Thanks

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, thanks for submitting your post-event report. We're glad it went well, and you learned something new. Great work!

Also, you don't need to tag me to review your reports; as soon as you submit them, I receive them and will attend to them as quickly as possible 😉.
