### ISSUE TITLE
HACKTOBERFEST EKITI 2021 | ADO EKITI - 2021/10/01

### ISSUE THREAD

**Issue by saintmalik** [oscafrica/chapter-leads-hub#66]
## Event information
_Please complete all applicable._

- **Event name**: HACKTOBERFEST EKITI 2021
- **Event description**:
- **Event date**: _21/10/01_ to _21/10/31_
- **Event time**: During participant's leisure time
- **Event duration**: During participant's leisure time
- **Event location**: Virtual
- **Estimated number of attendees**: 57

## How does this benefit your chapter?
_Please let us know why we should approve this event._

Seems like an auto approved event, Hacktoberfest Season 👀, but also the hacktoberfest event will help both beginners and new comers to open source to see how easy it is to get into open source and get rewared for thier contributions.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._

Nothing, its all virtual.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by saintmalik** [comment]
# Post Event Report [HACKTOBERFEST EKITI 2021] [2021/10/01]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_

well, looking that we collaborated with Four active tech community in Ekiti, we had 57 interested individuals in total, but upto 35 individuals from ekiti was actually active throughout the event while upto 10 external individuals also participated.

Also it we had both male and female participants, and our external participants are people from different part of the globe.

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_

it was all virtual, all fully managed on whatsapp, but also broadcasted on our Discord group.

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_

_Feel free to share your positive and negative experiences here with bullet points._
 
It was draining at some point, but see alot of guys making progress and coming to get things done was awesome, we actually collaborated and built this website: [Hacktoberfest Ekiti](https://hacktoberfest-ekiti.web.app/) and [Hacktoberfest Ekiti Documentation](https://hacktoberfest-ekiti.web.app/documentation). it was a collaborative efforts from our UI/UX guys, The Devs🤓, The Documentation guys, well it was an awesome event😌.

Some other individuals went forward to contribute to other projects and made waves, and positive contributions.

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_

I learnt more about how this collaborative thigs works, distributed tasks using GitHub issues and more.


## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_

https://twitter.com/osca_ado_ekiti/status/1446376966303723546

https://twitter.com/osca_ado_ekiti/status/1455072247610331142

## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_

![cojshshd](https://user-images.githubusercontent.com/37118134/147597730-d2670cb2-4cde-40ca-aa2b-cd26cb056b8f.jpg)
![dgsgd](https://user-images.githubusercontent.com/37118134/147597752-6ebb9b86-4472-45d6-8b5d-5de558c078c1.jpg)
![fddfdf](https://user-images.githubusercontent.com/37118134/147597756-c695a880-0b7a-464e-8b09-a22566b0f4fe.jpg)
![oscajjdjd](https://user-images.githubusercontent.com/37118134/147597759-d1258486-1532-4fd4-ab18-2e77e52d9bcf.jpg)

## Summary 🟡

_Generally, what's your overview of the event?_

It went well

_How did it go for you as a Chapter Lead?_

Nothing much, connected with new people

_Looking forward to the next event? What changes will you be making based on your experience from this event?_

**Comment by BolajiAyodeji** [comment]
Thanks for the amazing report @saintmalik! Great work with your event; we look forward to more this year 🙌🏾

**Comment by didicodes** [comment]
Hey @saintmalik. I trust you are doing great? 

I can see that you created an issue for your event and went ahead to approve it yourself without waiting for either @BolajiAyodeji or myself to respond and approve your event. Please do not do this again. 

We need to review your event and approve it before you go ahead and start making plans for the event. Do read our chapter leads handbook again to stay updated with the rules of opening an issue for an event. Thank you. 

Since you've already hosted this event, we will go ahead and overlook the mistake you made. It sure looks like it was an amazing event. Thank you for hosting it and spreading the word about Open Source in your community.

**Comment by saintmalik** [comment]
> Hey @saintmalik. I trust you are doing great?
> 
> I can see that you created an issue for your event and went ahead to approve it yourself without waiting for either @BolajiAyodeji or myself to respond and approve your event. Please do not do this again.
> 
> We need to review your event and approve it before you go ahead and start making plans for the event. Do read our chapter leads handbook again to stay updated with the rules of opening an issue for an event. Thank you.
> 
> Since you've already hosted this event, we will go ahead and overlook the mistake you made. It sure looks like it was an amazing event. Thank you for hosting it and spreading the word about Open Source in your community.

Thank you, am sorry for approving it myself, but the reason why i did that was because we've already hosted the event and i asked in our previous meetup, if i can submit the event report, you said i should go ahead.

Thats the reason, it wont happen again

**Comment by didicodes** [comment]
Ah, yes. I remember @saintmalik. Thanks for bringing that to my attention and apologies for the confusion. 

Do have a lovely day and let’s stick (you and I 😃 ) to the right procedure next time.

**Comment by saintmalik** [comment]
Thank you
