### ISSUE TITLE
INTRODUCTION TO OPEN SOURCE & HOW TO MAKE CONTRIBUTIONS TO OSS  | IKORODU - 2022/01/29

### ISSUE THREAD

**Issue by Boluwatifeh** [oscafrica/chapter-leads-hub#67]
## Event information

- **Event name**: INTRODUCTION TO OPEN SOURCE & HOW TO MAKE CONTRIBUTIONS TO OSS
- **Event description**: The event is an inagural event introducing attendees to the OSCA IKORODU chapter and also Open source. Basically the What, Why and How Open source and open source contrubutions is crucial and how they can benefit from it. 
- **Event date**: _2022/01/29_
- **Event time**: _1PM-2:30PM (GMT+1)_
- **Event duration**: 1 Hour 30 minutes
- **Event location**: Virtual (StreamYard)
- **Estimated number of attendees**:  30-50

## How does this benefit your chapter?
Open source contributions can be a rewarding way to learn, teach and gain experience in just about any skill imaginable. The event would benefit attendees because they would have an understanding of  what Open source entails, reason why it is pivotal to their careers and also ways in which they can leverage open source to turn their ideas into reality

## What help do you need with this event? 
It would be of immense importance  if Open Source Community Africa could help with sponsorship for the event, 

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @Boluwatifeh, thanks for submitting your event ticket.

Your event looks good to us and we're happy to approve it. As much as possible please try to make your designs in-house so you don't have to spend on that 😉. Good luck with your first event!

**Comment by Boluwatifeh** [comment]
Thanks a lot @BolajiAyodeji most of our volunteers in the community are not into design, but i'll try as much as possible to work on that.

**Comment by BolajiAyodeji** [comment]
That's fine. You can use this to pick up the skill yourself and practice. Remember we already have a [design guide](https://github.com/oscafrica/Design/blob/master/Chapters%20Program/OSCA%20Chapters%20Design%20Guide.pdf) that includes some templates you can use to easily get started :).

**Comment by Boluwatifeh** [comment]
Noted. Thanks for pointing that out 👍🏿  @BolajiAyodeji

**Comment by Boluwatifeh** [comment]
Hi @BolajiAyodeji concerning the sponsorship for this event, i haven't received any response, kindly help look into it. Thanks

**Comment by BolajiAyodeji** [comment]
Sponsorship is disbursed now! Apologies for the delays.

**Comment by Boluwatifeh** [comment]
Received, Thanks a lot 🥇

**Comment by Boluwatifeh** [comment]
# Post Event Report [INTRODUCTION TO OPEN SOURCE & HOW TO MAKE CONTRIBUTIONS TO OSS] [2022/01/29]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_
5 members joined the streaming which was low compared to the number of RSVP

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_
Streamyard platform was used which made the event seamless 

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_
There was a little drawback with one of the speakers, he reached out a day before the event that he couldn't make it to the event asking if we could reschedule but i couldn't reschedule due to the fact that the event was just in about 24 hours moreover we have a second speaker for the same event. so i decided we would host him again on our upcoming event while the second speaker stood up as the main speaker. Asides that, every other plans were fruitful. 
 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_
I learned how to design and work with figma for graphics design, in general, i also learnt a lot about the entire process of organizing an event (This is going to be my first time) 


## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._
Yes the attendees shared feedback about the event


*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 
During and after the event, i didn't think of planning a feedback survey but i'd incorporate that into future events. 

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_
Twitter: https://twitter.com/oscaikorodu/status/1487405966840799238?s=20&t=yeEKXfsT5mHXlNpz-LHW1A
Youtube: https://www.youtube.com/watch?v=XKTZc5IpcJI

## Summary 🟡

_Generally, what's your overview of the event?_
It was an exciting experience overall. 

_How did it go for you as a Chapter Lead?_
It went well for me as a chapter lead and i'm looking forward to organizing more events to better advocate about open source in my local community while leveraging the opportunity to develop better community management skills. 

_Looking forward to the next event? What changes will you be making based on your experience from this event?_
Based on my experience with this event. future events would be much more better and impactful going forward.

**Comment by BolajiAyodeji** [comment]
Hi @Boluwatifeh, thanks for submitting your report!

We're happy it was a success and you learned something new. I'm sure the next one would be much better; great work!

You haven't submitted your expense report yet. Why's that, please?
