### ISSUE TITLE
INTRODUCTION TO GIT / GITHUB | OSCA IKOT-EKPENE - 2022/01/31

### ISSUE THREAD

**Issue by favourmark05** [oscafrica/chapter-leads-hub#71]
## Event information
_Please complete all applicable._

- **Event name**: INTRODUCTION TO GIT AND GITHUB
- **Event description**:
- **Event date**: _2022/01/31_
- **Event time**: 7PM - 8PM (WAT)_
- **Event duration**: 1 HOUR
- **Event location**: ONLINE
- **Estimated number of attendees**:  50

## How does this benefit your chapter?
_Please let us know why we should approve this event._
GIT is a version control system that helps you manage and keep track of your source code history, and it will be of great importance for the community to have a solid understanding of how it works so they can work and collaborate with other developers. 
It will also be of great benefit if they understand git before they can contribute to any Open source project online.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
NONE

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by didicodes** [comment]
Your event sounds like an interesting one, @favourmark05. Understanding Git and GitHub is one of the fundamentals of striving in the open source space. 

Please go ahead and start making the arrangements for the event. We are looking forward to hearing about how it went. 😃

Before creating an issue, always delete this part. 👇 

![image](https://user-images.githubusercontent.com/28895379/150012356-191958f0-ca29-4d17-9d0e-ff9d293b7bcf.png)

**Comment by favourmark05** [comment]
@didicodes Noted with thanks

**Comment by favourmark05** [comment]
# Post Event Report [INTRODUCTION TO GIT / GITHUB] [2022/01/31]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_
There were 30 persons in attendance 8 ladies and 22 guys.

## Event Venue 🟣
_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_
The venue for the event was online(virtual)

## The Good, Bad, and Ugly 🔴
_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_
Everything went well as planned and the purpose for the event was achieved.


## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_
Nothing new was learnt from organising this event but a reminder that teamwork helps makes an event successful always.


## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 
A couple of them did show their appreciation to the organizing team for creating an opportunity for those with zero or little knowledge on a version control tool such as git.

## Social Media Highlights ⚫️
https://twitter.com/oscaIK/status/1488136792985505794?s=20&t=ULF42RR8MQYixc0BJ2bDlg
https://twitter.com/oscaIK/status/1486663748765065219?s=20&t=wn_Kiq3521pasZ-LqOqnXg
https://twitter.com/oscaIK/status/1486663834366533636?s=20&t=wn_Kiq3521pasZ-LqOqnXg

_Include links to any social posts about the event from any social media platform_

## Event Photos 🟢
_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_
https://drive.google.com/drive/folders/1U3wO57xoxcyLo5BBmTVoPOwwo8DqDyJC?usp=sharing

## Summary 🟡
The aims of this event were achieved and positive feedback have been recorded from attendees

**Comment by didicodes** [comment]
Yay! This was very pleasant to read. @favourmark05 

It is really great to see the amazing work you are doing in Ikot Ekpene. Thank you and please keep up the good work.
