### ISSUE TITLE
Azure Fundamentals and Cloud Concepts Training ­: Describe the Core Azure Architectural Components  | OSCA Nairobi- 2022/03/26

### ISSUE THREAD

**Issue by veldakarimi** [oscafrica/chapter-leads-hub#72]
## Event information
_Please complete all applicable._

- **Event name**: Azure Fundamentals and Cloud Concepts Training ­­: Describe the Core Azure Architectural Components 
- **Event description**: A partnership with Styava to have sessions with our members to train them in Azure architectural components
- **Event date**: _22/02/12_
- **Event time**: _2:00pm (EAT)_
- **Event duration**: 2hours
- **Event location**: virtual
- **Estimated number of attendees**:  60

## How does this benefit your chapter?
_This event will educate our community members on the architecture of Microsoft Azure and how to use it in their different open source projects_

## What help do you need with this event? 
_Mainly media support._

## Checklist

**Before you post the issue**: 
- [X] You have followed the issue title format.
- [X] You have applied the correct labels (Country, Type of Event, Requests).

**Before the event**: 
- [ ] Your event is approved.
- [ ] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @veldakarimi, your event looks good to me. I trust this will be beneficial to your members; great work!

**Comment by veldakarimi** [comment]
There is an issue with the partnership. But we are handling it.

**Comment by BolajiAyodeji** [comment]
> There is an issue with the partnership. But we are handling it.

Okay. Does that mean this and the other event is canceled?

**Comment by veldakarimi** [comment]
Yes so far

**Comment by BolajiAyodeji** [comment]
Alright. Do keep us posted. Well done!

**Comment by veldakarimi** [comment]
Definitely. 😇
