### ISSUE TITLE
Git and GitHub for beginners  | OSCA OKITIPUPA - 2022/02/11

### ISSUE THREAD

**Issue by olawanlejoel** [oscafrica/chapter-leads-hub#74]
## Event information
_Please complete all applicable._

- **Event name**: Git and GitHub for beginners
- **Event description**: This would be a beginner-friendly workshop to introduce members to Github and version control including markdown.
- **Event date**: _22/02/11_
- **Event time**: _7PM - 8PM (WAT)_
- **Event duration**: 1hr
- **Event location**: Google Meet
- **Estimated number of attendees**: 40

## How does this benefit your chapter?
Git and GitHub play an important role in open-source, the team felt it will be good to introduce beginners to GitHub, version control, and markdown so they can be able to work with GitHub confidently.

## What help do you need with this event? 
Nothing!

## Checklist

**Before you post the issue**: 
- [X] You have followed the issue title format.
- [X] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [X] Your event is approved.
- [ ] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [X] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @olawanlejoel, thanks for your event submission.

This looks good to me and is approved. Great work!

**Comment by olawanlejoel** [comment]
Thanks so much for approving this event, we have started working to ensure the success of the event, here is the flyer, other details will follow soon
![Git and GitHub - OSCA Okitipupa](https://user-images.githubusercontent.com/57611810/151700790-a177caa8-a2da-43aa-9977-88e1e844f3e7.jpg)
!

**Comment by olawanlejoel** [comment]
# Post Event Report [Git and GitHub for beginners] [2022/02/11]

## Attendance 🔵

About 30 attendees with a lecturer of Computer Science from a school outside the community. I took screenshots after almost everybody left, so I just had to switch screens to highlight what happened 😢 

## Event Venue 🟣

It held on Google Meet.

## The Good, Bad, and Ugly 🔴

The event went out perfectly as planned and attendee were able to understand how to work with Git and GitHub. As a bonus, we touched deployments because most participants asked questions channeled towards that aspect.
 

## TIL (Today I Learned) ⚪️

I learned to split responsibilities among community members.


## Feedback from Attendees 🟠

They all asked for another session to explore more GitHub and Git aspects.

## Social Media Highlights ⚫️

I doubt if this is supposed to be here, but I created a resource page that contains links to resources related to GitHub to give participant and others interested a sort of roadmap.

## Event Photos 🟢

![WhatsApp Image 2022-02-11 at 7 07 26 PM (1)](https://user-images.githubusercontent.com/57611810/153719368-21aa4885-31de-4d98-a8e3-d49aead0cf95.jpeg)
![WhatsApp Image 2022-02-11 at 7 07 26 PM](https://user-images.githubusercontent.com/57611810/153719369-aad2d0c4-39e7-4b5c-aa1f-8354e266d97b.jpeg)
![WhatsApp Image 2022-02-11 at 7 07 29 PM (1)](https://user-images.githubusercontent.com/57611810/153719371-30b17fd3-8434-4f33-9677-9053e1803c08.jpeg)
![WhatsApp Image 2022-02-11 at 7 07 29 PM](https://user-images.githubusercontent.com/57611810/153719372-d8e0e801-247b-4d34-a7bd-f51d34defc9d.jpeg)
![WhatsApp Image 2022-02-11 at 7 07 28 PM](https://user-images.githubusercontent.com/57611810/153719373-e4de7a08-2012-4eb4-bc90-4d7494514d28.jpeg)
![WhatsApp Image 2022-02-11 at 7 07 27 PM (1)](https://user-images.githubusercontent.com/57611810/153719374-0a1c455a-08f8-4c11-82c5-52395cd4cf47.jpeg)
![WhatsApp Image 2022-02-11 at 7 07 27 PM](https://user-images.githubusercontent.com/57611810/153719376-8183c93f-3b79-4155-b618-1306b7d75b25.jpeg)


## Summary 🟡

It was a successful one, and I was able to introduce OSCA festival event to participants

_How did it go for you as a Chapter Lead?_

It was Awesome.

**Comment by BolajiAyodeji** [comment]
Hi, @olawanlejoel, for the exciting report!

I'm glad this was a success, and you learned something as a Leader. Again, great work, and we look forward to more!

Btw, the "social media highlights" is a section where you get to add links to any social media post from attendees that talks about their experience from the event (either them sharing pictures, excerpts from the talk, or something else about the event).

**Comment by olawanlejoel** [comment]
Thanks so much. I will definitely include that for subsequent events.
