### ISSUE TITLE
GIT AND GITHUB FOR BEGINNERS | ADO EKITI - 2022/02/05

### ISSUE THREAD

**Issue by saintmalik** [oscafrica/chapter-leads-hub#75]
## Event information
_Please complete all applicable._

- **Event name**: GIT AND GITHUB FOR BEGINNERS
- **Event description**: This is a workshop to help beginners learn how to use git and github to make contributions to open source
- **Event date**: _22/02/05_
- **Event time**: _12:00 pm (WAT)_
- **Event duration**: An hour
- **Event location**: EKSU Techub
- **Estimated number of attendees**: 30

## How does this benefit your chapter?
_Please let us know why we should approve this event._

After taking a survey with my community, noticed all of them dont know how to use git and github to make contributions to open source, and git and github is an essential tool for making open source contribution.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Funding

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [x] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @saintmalik, thanks for submitting your event.

This looks to me and is approved. So, please proceed with planning; you'll hear from us about sponsorship soon!

**Comment by BolajiAyodeji** [comment]
Hi @saintmalik, thanks for sharing a detailed report!

We're happy to see that your first physical event went well. Great work!
