### ISSUE TITLE
OPEN SOURCE 101 | ADO EKITI - 2022/02/05

### ISSUE THREAD

**Issue by saintmalik** [oscafrica/chapter-leads-hub#76]
## Event information
_Please complete all applicable._

- **Event name**: OPEN SOURCE 101
- **Event description**: Giving a fresh start and introduction to community members about open souce, the why?, the what? and the how? of open source, benefits of open source and how the can get started to contributing to open source
- **Event date**: _22/02/05_
- **Event time**: _10:00 am (WAT)_
- **Event duration**: 1hr 30min
- **Event location**: EKSU Techub
- **Estimated number of attendees**: 30

## How does this benefit your chapter?
_Please let us know why we should approve this event._

We want to put every members of the community through what open source is, how open source can improve their careers, how to they can contribute as both technical and non technical individual, a detailed introduction of what open source is.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._

nothing

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [x] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @saintmalik, thanks for submitting your event.

This looks good and is approved. Great work!

**Comment by saintmalik** [comment]
Thank you😊

**Comment by saintmalik** [comment]
# Post Event Report [OPEN SOURCE 101] [05/02/2022]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_

Yeah, we had both genders present at our events, although the male attendees ws much than the female attendees, we had both tech experirenced and non expirenced attendees.

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_

We used the University TechHub, nothing, we didnt have any issues.

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_

Well no, the event was scheduled to start exactly by 10am but we later started by 11am 🙃

We budgeted for 30+ individuals and we ended up having 27 individuals showing up, leaving us with surplus refreshment packages

Our speaker couldnt make it to the event venue, so i ended up picking the session😁

_Feel free to share your positive and negative experiences here with bullet points._

Some attendees was able to learn something new, while some improved on what they already know about open source.
 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_

Always put african time to event schedules, if you plan on starting by 11 am, set the time of the event to 10:30am

Also i learnt i shouldnt always expect every single person that RSVPed to always show up at the events, things do happen


## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 

We did a Q&A session and we clearified alot of misconceptions

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_
https://twitter.com/osca_ado_ekiti/status/1489845782706589703
https://twitter.com/osca_ado_ekiti/status/1489866059188523008
https://twitter.com/osca_ado_ekiti/status/1489970202272014345

## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_

https://pbs.twimg.com/media/FK1v-plXEAAM15p?format=jpg
https://pbs.twimg.com/media/FK1v_KhXwAYyj7r?format=jpg
https://pbs.twimg.com/media/FK1v_j5XMAIDR1w?format=jpg
https://pbs.twimg.com/media/FK1v_6nWUAAtDQW?format=jpg
![image](https://user-images.githubusercontent.com/37118134/153371402-ec2f764d-76e4-4d6a-ade6-d1392e54944f.png)
https://pbs.twimg.com/media/FK1xNKoWUAwyctf?format=jpg
https://pbs.twimg.com/media/FK1xOCeXMAEF8k3?format=jpg
https://pbs.twimg.com/media/FK1xOp6XIAIzKaZ?format=jpg

## Summary 🟡

_Generally, what's your overview of the event?_

It went well

_How did it go for you as a Chapter Lead?_

It was a huge success, being the first physical event of OSCA Ado Ekiti

_Looking forward to the next event? What changes will you be making based on your experience from this event?_

Timing, Minimized Expectations

**Comment by BolajiAyodeji** [comment]
Hi @saintmalik, thanks for sharing a detailed report!

We're happy to see that your first physical event went well. Great work!
