### ISSUE TITLE
INTRODUCTION TO OPEN SOURCE TECHNOLOGY | OSCA BENIN-CITY - 2022/02/19

### ISSUE THREAD

**Issue by SkyC0der** [oscafrica/chapter-leads-hub#77]
## Event information
_Please complete all applicable._

- **Event name**: INTRODUCTION TO OPEN SOURCE TECHNOLOGY
- **Event date**: _2022/02/19_
- **Event time**: _10:00AM (GMT +1)_
- **Event duration**: 1hr
- **Event location**: Virtual
- **Estimated number of attendees**: 30-50
- **Event description**:  Open source contributions can be a rewarding way to learn, teach and gain experience in just about any skill imaginable. This will be the first open source event/meetup introducing people to what Open Source, OSCA and how to go about making meaningful Open Source Contributions. This event will centre on introducing Open Source Community to them, why they should contribute to open source, the benefit and importance of contributing to Open Source.

## How does this benefit your chapter?
_Please let us know why we should approve this event._
Open source contributions can be a rewarding way to learn, teach and gain experience in just about any skill imaginable. This will be the first open source event/meetup introducing people to what Open Source, OSCA and how to go about making meaningful Open Source Contributions. This event will centre on introducing Open Source Community to them, why they should contribute to open source, the benefit and importance of contributing to Open Source.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Publicity on social media platforms

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [x] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @SkyC0der, thanks for submitting your event.

This looks good to me and is approved! Goodluck on your first event :).

**Comment by SkyC0der** [comment]
# Post Event Report [ INTRODUCTION TO OPEN SOURCE TECHNOLOGY | OSCA BENIN-CITY ] [ 19/02/2022 ]



## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_

We were about 8-10 attendees. Female and Male attendees present.

## Event Venue 🟣

Google Meet. Experienced a slight network issue but it was restored in the end. 

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_
_Feel free to share your positive and negative experiences here with bullet points._

- The amount of people that RSVP didn't reflect in the attendees present
- The mail notifications didn't work, I should have sent another reminder email
- I was able to talk about the idea of Open Source Technology to people with no previous knowledge

 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_

- Sharpened my design skills by creating event flyers and preparing event slides.
- Learnt more about Open Source Contribution
- Learnt how to schedule events and create RSVP forms 

## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 

During the event, attendees suggested what they'd like to learn in the next event

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_
https://twitter.com/osca_benincity/status/1494745665750118407?t=Htl1ounaDw0VBAjEmhlLiQ&s=19

https://twitter.com/osca_benincity/status/1495065110863302660?t=pJ8oOaCyAxPXmsCYkzCLXQ&s=19

## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_

**Link to screenshots:** https://drive.google.com/folderview?id=1J_TJKsfBe-QPQ2-YgqF1eZYwE4FVXWMo
**Link to Slides**: https://www.figma.com/proto/aHkeEq3u5IR30ROG9gbHj0/OSCA-BENIN-CITY?node-id=0%3A1&scaling=min-zoom&page-id=0%3A1

## Summary 🟡

_Generally, what's your overview of the event?_
It was good for a start. A lot of room to improvement. The next event will definitely be better

_How did it go for you as a Chapter Lead?_

_Looking forward to the next event? What changes will you be making based on your experience from this event?_
I intend to start publicity early and target mostly student tech groups / communities to involve them in getting started with Open Source Technology

**Comment by BolajiAyodeji** [comment]
Hi @SkyC0der, thanks for submitting your report.

We're happy to see that your event went well and you learned a lot. Great work!
