### ISSUE TITLE
Leverage Open Source for Career Growth | OSCA Makurdi - 2022/02/26

### ISSUE THREAD

**Issue by logiquebox** [oscafrica/chapter-leads-hub#80]
## Event information
- **Event name**: Open Source for Career Growth
- **Event description**:  Open Source for Career Growth is aimed at giving community members an in-depth knowledge about open source, how to contribute to open source and leveraging all the benefits of open source for career growth while increasing the rate of credible contribution to open source
- **Event date**: _2022/02/26_
- **Event time**: _10:00 am (GMT)_
- **Event duration**: 2 hours
- **Event location**: Still in progress 
- **Estimated number of attendees**: 30+ Attendees 

## How does this benefit your chapter?
_Please let us know why we should approve this event._
This event will provide chapter members the opportunity to gain in-depth knowledge about open source and leverage it for growth and skill progression

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
This is a physical event and of course following the covid-19 protocols therefore, we would need **sponsorship** and **swags** for this event.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [x] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @logiquebox, thanks for submitting your event request.

This looks good to me and is approved. Good luck!

**Comment by BolajiAyodeji** [comment]
Yayyy! We're happy to see it went well. Great work and report @logiquebox!
