### ISSUE TITLE
Event budget template - suggestion 

### ISSUE THREAD

**Issue by logiquebox** [oscafrica/chapter-leads-hub#81]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to suggest and possibly add an event budget template to the useful links section of the chapter-leads-hub README.md file 

**Describe alternatives you've considered**

**Additional context**

**Comment by BolajiAyodeji** [comment]
Hi @logiquebox, sure, feel free to suggest a template!
