### ISSUE TITLE
Kickstarting your Career in UI/UX Design  | OSCA Makurdi - 23/02/2022

### ISSUE THREAD

**Issue by logiquebox** [oscafrica/chapter-leads-hub#86]
## Event information
_Please complete all applicable._

- **Event name**: Kickstarting your Career in UI/UX Design 
- **Event description**: This is a five (5) webinar series aimed at introducing members to starting a career in UI/UX design 
- **Event date**: _23/02/2022_
- **Event time**: _2:00pm_
- **Event duration**: 2 hours
- **Event location**: Google Meet (Online)
- **Estimated number of attendees**: 40+

## How does this benefit your chapter?
_Please let us know why we should approve this event._
UI/UX Design is a very lucrative field in the tech ecosystem today and this event provides an avenue for attendees to gain knowledge in this skill.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Publicity 

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by logiquebox** [comment]
![Bitdev-Flyer](https://user-images.githubusercontent.com/37655600/153104084-d5e5bc3a-dbc2-4ef4-8fc7-1eded7d9c6b4.jpg)

**Comment by BolajiAyodeji** [comment]
Hi @logiquebox, thanks for submitting your event.

I noticed you already started promoting this event even when it isn't approved yet. So please ensure to always wait for feedback and consider your event not ready to go until we review and approve it. This is to ensure we can advise you where required, and if it's already live, the feedback might be useless.

The event looks great and is approved. Goodluck :)

**Comment by logiquebox** [comment]
Correction taken and the mistake will not be repeated going forward.
Thanks for your feedback @BolajiAyodeji

**Comment by logiquebox** [comment]
# Post Event Report [Kickstarting Your Career in UI/UX Design] [23/02/2022]


## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_
Yeah, the attendance for the event was huge with diverse folks in attendance. And also the turnout for the event was great!

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_
The event was a virtual event held on Google meet(online), Things worked out quite well for the event, just a few network glitches but nothing out of our control.

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_
For me, this is the best virtual event I have hosted and moderated,  I mean it is way better than the first one 😃. It was an interactive and engaging session and the feedback was great.

 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_ 
I learned how to use slido.com to keep attendees engaged and not get them bored

## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_
![Screenshot 2022-02-23 175035](https://user-images.githubusercontent.com/37655600/156310978-12eedbec-fa74-4b34-afaf-f4244607d58a.png)
![Screenshot 2022-02-23 170751](https://user-images.githubusercontent.com/37655600/156311018-f077ab34-950a-4793-a1f0-f5e85d3ef7e1.png)

## Summary 🟡

_Generally, what's your overview of the event?_
The event was generally a huge success with a great number of attendees compared to our last virtual event

_How did it go for you as a Chapter Lead?_
The experience was great, and also growing because I'm learning to be more inclusive in my choice of words and actions when handling issues or events.

**Comment by BolajiAyodeji** [comment]
Thanks for submitting your report @logiquebox. Great work!
