### ISSUE TITLE
How to crack the 2022 GSoD application process | KAMPALA CHAPTER - 19/02/2022

### ISSUE THREAD

**Issue by KakoozaJerry** [oscafrica/chapter-leads-hub#90]
## Event information
A technical writers workshop on how to crack the 2022 GSoD application process

- **Event name**:A technical writers workshop on how to crack the 2022 GSoD application process
- **Event description**:
- **Event date**: _19/02/2022_
- **Event time**: _10:00 am (EAT+3)_
- **Event duration**: 2hours
- **Event location**:Google meet
- **Estimated number of attendees**: 20

## How does this benefit your chapter?
People will learn more about how to stand out in the technical writers space

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [ ] Your event is approved.
- [x] Your event's RSVP page has been created.
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @KakoozaJerry, you're submitting your event very late. You ought to have submitted 2 weeks minimum and 3 weeks maximum before your event date. Do you have some explanation why, please?

Also, I noticed you already started promoting this event even when it isn't approved yet. Please ensure to always wait for feedback and consider your event not ready to go until we review and approve it. This is to ensure we can advise you where required, and if it's already live, the feedback might be useless.

**Comment by KakoozaJerry** [comment]
@BolajiAyodeji, sorry for the late submission. We just had a quick chat in the community whatsapp group and the facilitator said it is ok to host one this weekend. It was totally abrupt and I had no way of pushing it further. It is a smaller group event so decision making was swift.

**Comment by KakoozaJerry** [comment]
@BolajiAyodeji well noted Sir. Will submit the upcoming events much earlier in the stipulated time. Thank you

**Comment by KakoozaJerry** [comment]
# Post Event Report [How to crack the 2022 GSoD application process] [19/02/2022]

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_

We had about 30 people on the google meet call , with only 5 ladies and the rest were male.

## Event Venue 🟣
Google meet

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_
The presenter was unable to share their screen during the event so they had to share their slides with our co lead who helped project them.


## The Good, Bad, and Ugly 🔴

We anticipated more people to show up due to the quality of the content that was shared but I think the low turn up was due to a coinciding event of a python ladies community which our speaker heads hence less females.

_Feel free to share your positive and negative experiences here with bullet points._
 

## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_
I learnt how to make a public link that one can click and they add the event to their own calendar. This was so awesome. Also , I was able to do a recording session on google meet with tl:dv for the first time hence no need to rely on the zoom that required a paid version.

## Feedback from Attendees 🟠
They loved the event. It was so informative and interactive.

They proposed a physical session for the future events.

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 
During the event within the Q and A session

## Summary 🟡

_Generally, what's your overview of the event?_
It was a great event with quite engaged participants and a great speaker who has a vast amount of experience

_How did it go for you as a Chapter Lead?_
It was great since the issues with the link and the google meet were identified before hand and I addressed them well.

_Looking forward to the next event? What changes will you be making based on your experience from this event?_

**Comment by BolajiAyodeji** [comment]
Hi @KakoozaJerry, thanks for the detailed report! We're glad it went well and you're learning a lot :).
